export const WORKER_CONTROL_SUBMISSION_CEILING = 0;
export const WORKER_RESIZE_SUBMISSION_CEILING = 0;
export const MAIN_STABLE_FRAME_PERCENT_FLOOR = 90;
export const WORKER_STABLE_FRAME_PERCENT_FLOOR = 50;
