[package]
name = "pod-server"
version.workspace = true
edition.workspace = true

[[bin]]
name = "pod-server"
path = "src/main.rs"

[dependencies]
pod-core = { path = "../../crates/pod-core" }
pod-net = { path = "../../crates/pod-net" }
log.workspace = true
env_logger.workspace = true
glam.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
ctrlc = "3.4"
