// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ability_target_kind_type::AbilityTargetKind;
use super::action_kind_type::ActionKind;
use super::action_submission_row_type::ActionSubmissionRow;
use super::speak_volume_type::SpeakVolume;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `action_submission`.
///
/// Obtain a handle from the [`ActionSubmissionTableAccess::action_submission`] method on [`super::RemoteTables`],
/// like `ctx.db.action_submission()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.action_submission().on_insert(...)`.
pub struct ActionSubmissionTableHandle<'ctx> {
    imp: __sdk::TableHandle<ActionSubmissionRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `action_submission`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ActionSubmissionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ActionSubmissionTableHandle`], which mediates access to the table `action_submission`.
    fn action_submission(&self) -> ActionSubmissionTableHandle<'_>;
}

impl ActionSubmissionTableAccess for super::RemoteTables {
    fn action_submission(&self) -> ActionSubmissionTableHandle<'_> {
        ActionSubmissionTableHandle {
            imp: self
                .imp
                .get_table::<ActionSubmissionRow>("action_submission"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ActionSubmissionInsertCallbackId(__sdk::CallbackId);
pub struct ActionSubmissionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ActionSubmissionTableHandle<'ctx> {
    type Row = ActionSubmissionRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ActionSubmissionRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ActionSubmissionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActionSubmissionInsertCallbackId {
        ActionSubmissionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ActionSubmissionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ActionSubmissionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActionSubmissionDeleteCallbackId {
        ActionSubmissionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ActionSubmissionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ActionSubmissionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ActionSubmissionTableHandle<'ctx> {
    type UpdateCallbackId = ActionSubmissionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ActionSubmissionUpdateCallbackId {
        ActionSubmissionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ActionSubmissionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `submission_id` unique index on the table `action_submission`,
/// which allows point queries on the field of the same name
/// via the [`ActionSubmissionSubmissionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.action_submission().submission_id().find(...)`.
pub struct ActionSubmissionSubmissionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ActionSubmissionRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ActionSubmissionTableHandle<'ctx> {
    /// Get a handle on the `submission_id` unique index on the table `action_submission`.
    pub fn submission_id(&self) -> ActionSubmissionSubmissionIdUnique<'ctx> {
        ActionSubmissionSubmissionIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("submission_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ActionSubmissionSubmissionIdUnique<'ctx> {
    /// Find the subscribed row whose `submission_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ActionSubmissionRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ActionSubmissionRow>("action_submission");
    _table.add_unique_constraint::<u64>("submission_id", |row| &row.submission_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ActionSubmissionRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ActionSubmissionRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ActionSubmissionRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait action_submissionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ActionSubmissionRow`.
    fn action_submission(&self) -> __sdk::__query_builder::Table<ActionSubmissionRow>;
}

impl action_submissionQueryTableAccess for __sdk::QueryTableAccessor {
    fn action_submission(&self) -> __sdk::__query_builder::Table<ActionSubmissionRow> {
        __sdk::__query_builder::Table::new("action_submission")
    }
}
