// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
#[derive(Copy, Eq, Hash)]
pub enum ActionKind {
    Move,

    Stop,

    Rotate,

    LookAt,

    Attack,

    AttackTarget,

    UseAbility,

    CaptureCreature,

    SummonCompanion,

    CommandCompanion,

    Interact,

    InteractWith,

    Pickup,

    Drop,

    UseItem,

    GatherResource,

    Loot,

    Speak,

    Signal,

    SetAutoRetaliate,

    Idle,

    Spawn,
}

impl __sdk::InModule for ActionKind {
    type Module = super::RemoteModule;
}
