// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::ability_target_kind_type::AbilityTargetKind;
use super::action_kind_type::ActionKind;
use super::speak_volume_type::SpeakVolume;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ActionSubmissionRow {
    pub submission_id: u64,
    pub entity_id: u64,
    pub tick: u64,
    pub action_kind: ActionKind,
    pub direction_x: Option<f32>,
    pub direction_y: Option<f32>,
    pub angle: Option<f32>,
    pub target_x: Option<f32>,
    pub target_y: Option<f32>,
    pub target_entity_id: Option<u64>,
    pub ability_slot: Option<u8>,
    pub ability_target_kind: Option<AbilityTargetKind>,
    pub message: Option<String>,
    pub volume: Option<SpeakVolume>,
    pub signal_type: Option<String>,
    pub signal_data: Option<String>,
    pub prefab: Option<String>,
}

impl __sdk::InModule for ActionSubmissionRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ActionSubmissionRow`.
///
/// Provides typed access to columns for query building.
pub struct ActionSubmissionRowCols {
    pub submission_id: __sdk::__query_builder::Col<ActionSubmissionRow, u64>,
    pub entity_id: __sdk::__query_builder::Col<ActionSubmissionRow, u64>,
    pub tick: __sdk::__query_builder::Col<ActionSubmissionRow, u64>,
    pub action_kind: __sdk::__query_builder::Col<ActionSubmissionRow, ActionKind>,
    pub direction_x: __sdk::__query_builder::Col<ActionSubmissionRow, Option<f32>>,
    pub direction_y: __sdk::__query_builder::Col<ActionSubmissionRow, Option<f32>>,
    pub angle: __sdk::__query_builder::Col<ActionSubmissionRow, Option<f32>>,
    pub target_x: __sdk::__query_builder::Col<ActionSubmissionRow, Option<f32>>,
    pub target_y: __sdk::__query_builder::Col<ActionSubmissionRow, Option<f32>>,
    pub target_entity_id: __sdk::__query_builder::Col<ActionSubmissionRow, Option<u64>>,
    pub ability_slot: __sdk::__query_builder::Col<ActionSubmissionRow, Option<u8>>,
    pub ability_target_kind:
        __sdk::__query_builder::Col<ActionSubmissionRow, Option<AbilityTargetKind>>,
    pub message: __sdk::__query_builder::Col<ActionSubmissionRow, Option<String>>,
    pub volume: __sdk::__query_builder::Col<ActionSubmissionRow, Option<SpeakVolume>>,
    pub signal_type: __sdk::__query_builder::Col<ActionSubmissionRow, Option<String>>,
    pub signal_data: __sdk::__query_builder::Col<ActionSubmissionRow, Option<String>>,
    pub prefab: __sdk::__query_builder::Col<ActionSubmissionRow, Option<String>>,
}

impl __sdk::__query_builder::HasCols for ActionSubmissionRow {
    type Cols = ActionSubmissionRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ActionSubmissionRowCols {
            submission_id: __sdk::__query_builder::Col::new(table_name, "submission_id"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            tick: __sdk::__query_builder::Col::new(table_name, "tick"),
            action_kind: __sdk::__query_builder::Col::new(table_name, "action_kind"),
            direction_x: __sdk::__query_builder::Col::new(table_name, "direction_x"),
            direction_y: __sdk::__query_builder::Col::new(table_name, "direction_y"),
            angle: __sdk::__query_builder::Col::new(table_name, "angle"),
            target_x: __sdk::__query_builder::Col::new(table_name, "target_x"),
            target_y: __sdk::__query_builder::Col::new(table_name, "target_y"),
            target_entity_id: __sdk::__query_builder::Col::new(table_name, "target_entity_id"),
            ability_slot: __sdk::__query_builder::Col::new(table_name, "ability_slot"),
            ability_target_kind: __sdk::__query_builder::Col::new(
                table_name,
                "ability_target_kind",
            ),
            message: __sdk::__query_builder::Col::new(table_name, "message"),
            volume: __sdk::__query_builder::Col::new(table_name, "volume"),
            signal_type: __sdk::__query_builder::Col::new(table_name, "signal_type"),
            signal_data: __sdk::__query_builder::Col::new(table_name, "signal_data"),
            prefab: __sdk::__query_builder::Col::new(table_name, "prefab"),
        }
    }
}

/// Indexed column accessor struct for the table `ActionSubmissionRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct ActionSubmissionRowIxCols {
    pub submission_id: __sdk::__query_builder::IxCol<ActionSubmissionRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for ActionSubmissionRow {
    type IxCols = ActionSubmissionRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ActionSubmissionRowIxCols {
            submission_id: __sdk::__query_builder::IxCol::new(table_name, "submission_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ActionSubmissionRow {}
