// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::agent_tool_call_event_row_type::AgentToolCallEventRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `agent_tool_call_event`.
///
/// Obtain a handle from the [`AgentToolCallEventTableAccess::agent_tool_call_event`] method on [`super::RemoteTables`],
/// like `ctx.db.agent_tool_call_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agent_tool_call_event().on_insert(...)`.
pub struct AgentToolCallEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<AgentToolCallEventRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `agent_tool_call_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AgentToolCallEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AgentToolCallEventTableHandle`], which mediates access to the table `agent_tool_call_event`.
    fn agent_tool_call_event(&self) -> AgentToolCallEventTableHandle<'_>;
}

impl AgentToolCallEventTableAccess for super::RemoteTables {
    fn agent_tool_call_event(&self) -> AgentToolCallEventTableHandle<'_> {
        AgentToolCallEventTableHandle {
            imp: self
                .imp
                .get_table::<AgentToolCallEventRow>("agent_tool_call_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AgentToolCallEventInsertCallbackId(__sdk::CallbackId);
pub struct AgentToolCallEventDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AgentToolCallEventTableHandle<'ctx> {
    type Row = AgentToolCallEventRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AgentToolCallEventRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AgentToolCallEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentToolCallEventInsertCallbackId {
        AgentToolCallEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AgentToolCallEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AgentToolCallEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentToolCallEventDeleteCallbackId {
        AgentToolCallEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AgentToolCallEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AgentToolCallEventUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AgentToolCallEventTableHandle<'ctx> {
    type UpdateCallbackId = AgentToolCallEventUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AgentToolCallEventUpdateCallbackId {
        AgentToolCallEventUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AgentToolCallEventUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `row_id` unique index on the table `agent_tool_call_event`,
/// which allows point queries on the field of the same name
/// via the [`AgentToolCallEventRowIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agent_tool_call_event().row_id().find(...)`.
pub struct AgentToolCallEventRowIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AgentToolCallEventRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AgentToolCallEventTableHandle<'ctx> {
    /// Get a handle on the `row_id` unique index on the table `agent_tool_call_event`.
    pub fn row_id(&self) -> AgentToolCallEventRowIdUnique<'ctx> {
        AgentToolCallEventRowIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("row_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AgentToolCallEventRowIdUnique<'ctx> {
    /// Find the subscribed row whose `row_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<AgentToolCallEventRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AgentToolCallEventRow>("agent_tool_call_event");
    _table.add_unique_constraint::<u64>("row_id", |row| &row.row_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AgentToolCallEventRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AgentToolCallEventRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AgentToolCallEventRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait agent_tool_call_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AgentToolCallEventRow`.
    fn agent_tool_call_event(&self) -> __sdk::__query_builder::Table<AgentToolCallEventRow>;
}

impl agent_tool_call_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn agent_tool_call_event(&self) -> __sdk::__query_builder::Table<AgentToolCallEventRow> {
        __sdk::__query_builder::Table::new("agent_tool_call_event")
    }
}
