// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::agent_constraints_row_type::AgentConstraintsRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `agent_constraints`.
///
/// Obtain a handle from the [`AgentConstraintsTableAccess::agent_constraints`] method on [`super::RemoteTables`],
/// like `ctx.db.agent_constraints()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agent_constraints().on_insert(...)`.
pub struct AgentConstraintsTableHandle<'ctx> {
    imp: __sdk::TableHandle<AgentConstraintsRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `agent_constraints`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AgentConstraintsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AgentConstraintsTableHandle`], which mediates access to the table `agent_constraints`.
    fn agent_constraints(&self) -> AgentConstraintsTableHandle<'_>;
}

impl AgentConstraintsTableAccess for super::RemoteTables {
    fn agent_constraints(&self) -> AgentConstraintsTableHandle<'_> {
        AgentConstraintsTableHandle {
            imp: self
                .imp
                .get_table::<AgentConstraintsRow>("agent_constraints"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AgentConstraintsInsertCallbackId(__sdk::CallbackId);
pub struct AgentConstraintsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AgentConstraintsTableHandle<'ctx> {
    type Row = AgentConstraintsRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AgentConstraintsRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AgentConstraintsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentConstraintsInsertCallbackId {
        AgentConstraintsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AgentConstraintsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AgentConstraintsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentConstraintsDeleteCallbackId {
        AgentConstraintsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AgentConstraintsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AgentConstraintsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AgentConstraintsTableHandle<'ctx> {
    type UpdateCallbackId = AgentConstraintsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AgentConstraintsUpdateCallbackId {
        AgentConstraintsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AgentConstraintsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `agent_constraints`,
/// which allows point queries on the field of the same name
/// via the [`AgentConstraintsEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agent_constraints().entity_id().find(...)`.
pub struct AgentConstraintsEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AgentConstraintsRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AgentConstraintsTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `agent_constraints`.
    pub fn entity_id(&self) -> AgentConstraintsEntityIdUnique<'ctx> {
        AgentConstraintsEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AgentConstraintsEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<AgentConstraintsRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AgentConstraintsRow>("agent_constraints");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AgentConstraintsRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AgentConstraintsRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AgentConstraintsRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait agent_constraintsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AgentConstraintsRow`.
    fn agent_constraints(&self) -> __sdk::__query_builder::Table<AgentConstraintsRow>;
}

impl agent_constraintsQueryTableAccess for __sdk::QueryTableAccessor {
    fn agent_constraints(&self) -> __sdk::__query_builder::Table<AgentConstraintsRow> {
        __sdk::__query_builder::Table::new("agent_constraints")
    }
}
