// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AgentConstraintsRow {
    pub entity_id: u64,
    pub actions_per_tick: u8,
    pub attack_cooldown: u32,
    pub ability_cooldowns_json: String,
    pub can_act: bool,
    pub attack_cooldown_remaining: u32,
}

impl __sdk::InModule for AgentConstraintsRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AgentConstraintsRow`.
///
/// Provides typed access to columns for query building.
pub struct AgentConstraintsRowCols {
    pub entity_id: __sdk::__query_builder::Col<AgentConstraintsRow, u64>,
    pub actions_per_tick: __sdk::__query_builder::Col<AgentConstraintsRow, u8>,
    pub attack_cooldown: __sdk::__query_builder::Col<AgentConstraintsRow, u32>,
    pub ability_cooldowns_json: __sdk::__query_builder::Col<AgentConstraintsRow, String>,
    pub can_act: __sdk::__query_builder::Col<AgentConstraintsRow, bool>,
    pub attack_cooldown_remaining: __sdk::__query_builder::Col<AgentConstraintsRow, u32>,
}

impl __sdk::__query_builder::HasCols for AgentConstraintsRow {
    type Cols = AgentConstraintsRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AgentConstraintsRowCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            actions_per_tick: __sdk::__query_builder::Col::new(table_name, "actions_per_tick"),
            attack_cooldown: __sdk::__query_builder::Col::new(table_name, "attack_cooldown"),
            ability_cooldowns_json: __sdk::__query_builder::Col::new(
                table_name,
                "ability_cooldowns_json",
            ),
            can_act: __sdk::__query_builder::Col::new(table_name, "can_act"),
            attack_cooldown_remaining: __sdk::__query_builder::Col::new(
                table_name,
                "attack_cooldown_remaining",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `AgentConstraintsRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct AgentConstraintsRowIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<AgentConstraintsRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for AgentConstraintsRow {
    type IxCols = AgentConstraintsRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AgentConstraintsRowIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AgentConstraintsRow {}
