// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::agent_tick_rollup_row_type::AgentTickRollupRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `agent_tick_rollup`.
///
/// Obtain a handle from the [`AgentTickRollupTableAccess::agent_tick_rollup`] method on [`super::RemoteTables`],
/// like `ctx.db.agent_tick_rollup()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agent_tick_rollup().on_insert(...)`.
pub struct AgentTickRollupTableHandle<'ctx> {
    imp: __sdk::TableHandle<AgentTickRollupRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `agent_tick_rollup`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AgentTickRollupTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AgentTickRollupTableHandle`], which mediates access to the table `agent_tick_rollup`.
    fn agent_tick_rollup(&self) -> AgentTickRollupTableHandle<'_>;
}

impl AgentTickRollupTableAccess for super::RemoteTables {
    fn agent_tick_rollup(&self) -> AgentTickRollupTableHandle<'_> {
        AgentTickRollupTableHandle {
            imp: self
                .imp
                .get_table::<AgentTickRollupRow>("agent_tick_rollup"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AgentTickRollupInsertCallbackId(__sdk::CallbackId);
pub struct AgentTickRollupDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AgentTickRollupTableHandle<'ctx> {
    type Row = AgentTickRollupRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AgentTickRollupRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AgentTickRollupInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentTickRollupInsertCallbackId {
        AgentTickRollupInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AgentTickRollupInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AgentTickRollupDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentTickRollupDeleteCallbackId {
        AgentTickRollupDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AgentTickRollupDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AgentTickRollupUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AgentTickRollupTableHandle<'ctx> {
    type UpdateCallbackId = AgentTickRollupUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AgentTickRollupUpdateCallbackId {
        AgentTickRollupUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AgentTickRollupUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `row_id` unique index on the table `agent_tick_rollup`,
/// which allows point queries on the field of the same name
/// via the [`AgentTickRollupRowIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agent_tick_rollup().row_id().find(...)`.
pub struct AgentTickRollupRowIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AgentTickRollupRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AgentTickRollupTableHandle<'ctx> {
    /// Get a handle on the `row_id` unique index on the table `agent_tick_rollup`.
    pub fn row_id(&self) -> AgentTickRollupRowIdUnique<'ctx> {
        AgentTickRollupRowIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("row_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AgentTickRollupRowIdUnique<'ctx> {
    /// Find the subscribed row whose `row_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<AgentTickRollupRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AgentTickRollupRow>("agent_tick_rollup");
    _table.add_unique_constraint::<u64>("row_id", |row| &row.row_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AgentTickRollupRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AgentTickRollupRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AgentTickRollupRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait agent_tick_rollupQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AgentTickRollupRow`.
    fn agent_tick_rollup(&self) -> __sdk::__query_builder::Table<AgentTickRollupRow>;
}

impl agent_tick_rollupQueryTableAccess for __sdk::QueryTableAccessor {
    fn agent_tick_rollup(&self) -> __sdk::__query_builder::Table<AgentTickRollupRow> {
        __sdk::__query_builder::Table::new("agent_tick_rollup")
    }
}
