// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AgentToolCallEventRow {
    pub row_id: u64,
    pub tick: u64,
    pub agent_entity_id: u64,
    pub tool_name: String,
    pub provider: String,
    pub status: String,
    pub latency_ms: u32,
    pub request_units: u32,
    pub response_units: u32,
    pub data_json: String,
}

impl __sdk::InModule for AgentToolCallEventRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AgentToolCallEventRow`.
///
/// Provides typed access to columns for query building.
pub struct AgentToolCallEventRowCols {
    pub row_id: __sdk::__query_builder::Col<AgentToolCallEventRow, u64>,
    pub tick: __sdk::__query_builder::Col<AgentToolCallEventRow, u64>,
    pub agent_entity_id: __sdk::__query_builder::Col<AgentToolCallEventRow, u64>,
    pub tool_name: __sdk::__query_builder::Col<AgentToolCallEventRow, String>,
    pub provider: __sdk::__query_builder::Col<AgentToolCallEventRow, String>,
    pub status: __sdk::__query_builder::Col<AgentToolCallEventRow, String>,
    pub latency_ms: __sdk::__query_builder::Col<AgentToolCallEventRow, u32>,
    pub request_units: __sdk::__query_builder::Col<AgentToolCallEventRow, u32>,
    pub response_units: __sdk::__query_builder::Col<AgentToolCallEventRow, u32>,
    pub data_json: __sdk::__query_builder::Col<AgentToolCallEventRow, String>,
}

impl __sdk::__query_builder::HasCols for AgentToolCallEventRow {
    type Cols = AgentToolCallEventRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AgentToolCallEventRowCols {
            row_id: __sdk::__query_builder::Col::new(table_name, "row_id"),
            tick: __sdk::__query_builder::Col::new(table_name, "tick"),
            agent_entity_id: __sdk::__query_builder::Col::new(table_name, "agent_entity_id"),
            tool_name: __sdk::__query_builder::Col::new(table_name, "tool_name"),
            provider: __sdk::__query_builder::Col::new(table_name, "provider"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            latency_ms: __sdk::__query_builder::Col::new(table_name, "latency_ms"),
            request_units: __sdk::__query_builder::Col::new(table_name, "request_units"),
            response_units: __sdk::__query_builder::Col::new(table_name, "response_units"),
            data_json: __sdk::__query_builder::Col::new(table_name, "data_json"),
        }
    }
}

/// Indexed column accessor struct for the table `AgentToolCallEventRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct AgentToolCallEventRowIxCols {
    pub row_id: __sdk::__query_builder::IxCol<AgentToolCallEventRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for AgentToolCallEventRow {
    type IxCols = AgentToolCallEventRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AgentToolCallEventRowIxCols {
            row_id: __sdk::__query_builder::IxCol::new(table_name, "row_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AgentToolCallEventRow {}
