// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AgentTickRollupRow {
    pub row_id: u64,
    pub tick_start: u64,
    pub tick_end: u64,
    pub agent_entity_id: u64,
    pub total_distance: f32,
    pub submitted_action_count: u32,
    pub executed_action_count: u32,
    pub rejected_action_count: u32,
    pub tool_call_count: u32,
    pub tool_error_count: u32,
    pub rollup_json: String,
}

impl __sdk::InModule for AgentTickRollupRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AgentTickRollupRow`.
///
/// Provides typed access to columns for query building.
pub struct AgentTickRollupRowCols {
    pub row_id: __sdk::__query_builder::Col<AgentTickRollupRow, u64>,
    pub tick_start: __sdk::__query_builder::Col<AgentTickRollupRow, u64>,
    pub tick_end: __sdk::__query_builder::Col<AgentTickRollupRow, u64>,
    pub agent_entity_id: __sdk::__query_builder::Col<AgentTickRollupRow, u64>,
    pub total_distance: __sdk::__query_builder::Col<AgentTickRollupRow, f32>,
    pub submitted_action_count: __sdk::__query_builder::Col<AgentTickRollupRow, u32>,
    pub executed_action_count: __sdk::__query_builder::Col<AgentTickRollupRow, u32>,
    pub rejected_action_count: __sdk::__query_builder::Col<AgentTickRollupRow, u32>,
    pub tool_call_count: __sdk::__query_builder::Col<AgentTickRollupRow, u32>,
    pub tool_error_count: __sdk::__query_builder::Col<AgentTickRollupRow, u32>,
    pub rollup_json: __sdk::__query_builder::Col<AgentTickRollupRow, String>,
}

impl __sdk::__query_builder::HasCols for AgentTickRollupRow {
    type Cols = AgentTickRollupRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AgentTickRollupRowCols {
            row_id: __sdk::__query_builder::Col::new(table_name, "row_id"),
            tick_start: __sdk::__query_builder::Col::new(table_name, "tick_start"),
            tick_end: __sdk::__query_builder::Col::new(table_name, "tick_end"),
            agent_entity_id: __sdk::__query_builder::Col::new(table_name, "agent_entity_id"),
            total_distance: __sdk::__query_builder::Col::new(table_name, "total_distance"),
            submitted_action_count: __sdk::__query_builder::Col::new(
                table_name,
                "submitted_action_count",
            ),
            executed_action_count: __sdk::__query_builder::Col::new(
                table_name,
                "executed_action_count",
            ),
            rejected_action_count: __sdk::__query_builder::Col::new(
                table_name,
                "rejected_action_count",
            ),
            tool_call_count: __sdk::__query_builder::Col::new(table_name, "tool_call_count"),
            tool_error_count: __sdk::__query_builder::Col::new(table_name, "tool_error_count"),
            rollup_json: __sdk::__query_builder::Col::new(table_name, "rollup_json"),
        }
    }
}

/// Indexed column accessor struct for the table `AgentTickRollupRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct AgentTickRollupRowIxCols {
    pub row_id: __sdk::__query_builder::IxCol<AgentTickRollupRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for AgentTickRollupRow {
    type IxCols = AgentTickRollupRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AgentTickRollupRowIxCols {
            row_id: __sdk::__query_builder::IxCol::new(table_name, "row_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AgentTickRollupRow {}
