// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AgentTelemetryTickRow {
    pub row_id: u64,
    pub tick: u64,
    pub agent_entity_id: u64,
    pub visible_entity_count: u32,
    pub audible_event_count: u32,
    pub message_count: u32,
    pub submitted_action_count: u32,
    pub executed_action_count: u32,
    pub rejected_action_count: u32,
    pub trajectory_start_x: f32,
    pub trajectory_start_y: f32,
    pub trajectory_end_x: f32,
    pub trajectory_end_y: f32,
    pub frame_json: String,
}

impl __sdk::InModule for AgentTelemetryTickRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AgentTelemetryTickRow`.
///
/// Provides typed access to columns for query building.
pub struct AgentTelemetryTickRowCols {
    pub row_id: __sdk::__query_builder::Col<AgentTelemetryTickRow, u64>,
    pub tick: __sdk::__query_builder::Col<AgentTelemetryTickRow, u64>,
    pub agent_entity_id: __sdk::__query_builder::Col<AgentTelemetryTickRow, u64>,
    pub visible_entity_count: __sdk::__query_builder::Col<AgentTelemetryTickRow, u32>,
    pub audible_event_count: __sdk::__query_builder::Col<AgentTelemetryTickRow, u32>,
    pub message_count: __sdk::__query_builder::Col<AgentTelemetryTickRow, u32>,
    pub submitted_action_count: __sdk::__query_builder::Col<AgentTelemetryTickRow, u32>,
    pub executed_action_count: __sdk::__query_builder::Col<AgentTelemetryTickRow, u32>,
    pub rejected_action_count: __sdk::__query_builder::Col<AgentTelemetryTickRow, u32>,
    pub trajectory_start_x: __sdk::__query_builder::Col<AgentTelemetryTickRow, f32>,
    pub trajectory_start_y: __sdk::__query_builder::Col<AgentTelemetryTickRow, f32>,
    pub trajectory_end_x: __sdk::__query_builder::Col<AgentTelemetryTickRow, f32>,
    pub trajectory_end_y: __sdk::__query_builder::Col<AgentTelemetryTickRow, f32>,
    pub frame_json: __sdk::__query_builder::Col<AgentTelemetryTickRow, String>,
}

impl __sdk::__query_builder::HasCols for AgentTelemetryTickRow {
    type Cols = AgentTelemetryTickRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AgentTelemetryTickRowCols {
            row_id: __sdk::__query_builder::Col::new(table_name, "row_id"),
            tick: __sdk::__query_builder::Col::new(table_name, "tick"),
            agent_entity_id: __sdk::__query_builder::Col::new(table_name, "agent_entity_id"),
            visible_entity_count: __sdk::__query_builder::Col::new(
                table_name,
                "visible_entity_count",
            ),
            audible_event_count: __sdk::__query_builder::Col::new(
                table_name,
                "audible_event_count",
            ),
            message_count: __sdk::__query_builder::Col::new(table_name, "message_count"),
            submitted_action_count: __sdk::__query_builder::Col::new(
                table_name,
                "submitted_action_count",
            ),
            executed_action_count: __sdk::__query_builder::Col::new(
                table_name,
                "executed_action_count",
            ),
            rejected_action_count: __sdk::__query_builder::Col::new(
                table_name,
                "rejected_action_count",
            ),
            trajectory_start_x: __sdk::__query_builder::Col::new(table_name, "trajectory_start_x"),
            trajectory_start_y: __sdk::__query_builder::Col::new(table_name, "trajectory_start_y"),
            trajectory_end_x: __sdk::__query_builder::Col::new(table_name, "trajectory_end_x"),
            trajectory_end_y: __sdk::__query_builder::Col::new(table_name, "trajectory_end_y"),
            frame_json: __sdk::__query_builder::Col::new(table_name, "frame_json"),
        }
    }
}

/// Indexed column accessor struct for the table `AgentTelemetryTickRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct AgentTelemetryTickRowIxCols {
    pub row_id: __sdk::__query_builder::IxCol<AgentTelemetryTickRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for AgentTelemetryTickRow {
    type IxCols = AgentTelemetryTickRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AgentTelemetryTickRowIxCols {
            row_id: __sdk::__query_builder::IxCol::new(table_name, "row_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AgentTelemetryTickRow {}
