// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::collider_shape_kind_type::ColliderShapeKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ColliderRow {
    pub entity_id: u64,
    pub shape_kind: ColliderShapeKind,
    pub shape_radius: f32,
    pub shape_half_width: f32,
    pub shape_half_height: f32,
    pub is_trigger: bool,
    pub collision_group: u32,
    pub collision_mask: u32,
}

impl __sdk::InModule for ColliderRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ColliderRow`.
///
/// Provides typed access to columns for query building.
pub struct ColliderRowCols {
    pub entity_id: __sdk::__query_builder::Col<ColliderRow, u64>,
    pub shape_kind: __sdk::__query_builder::Col<ColliderRow, ColliderShapeKind>,
    pub shape_radius: __sdk::__query_builder::Col<ColliderRow, f32>,
    pub shape_half_width: __sdk::__query_builder::Col<ColliderRow, f32>,
    pub shape_half_height: __sdk::__query_builder::Col<ColliderRow, f32>,
    pub is_trigger: __sdk::__query_builder::Col<ColliderRow, bool>,
    pub collision_group: __sdk::__query_builder::Col<ColliderRow, u32>,
    pub collision_mask: __sdk::__query_builder::Col<ColliderRow, u32>,
}

impl __sdk::__query_builder::HasCols for ColliderRow {
    type Cols = ColliderRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ColliderRowCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            shape_kind: __sdk::__query_builder::Col::new(table_name, "shape_kind"),
            shape_radius: __sdk::__query_builder::Col::new(table_name, "shape_radius"),
            shape_half_width: __sdk::__query_builder::Col::new(table_name, "shape_half_width"),
            shape_half_height: __sdk::__query_builder::Col::new(table_name, "shape_half_height"),
            is_trigger: __sdk::__query_builder::Col::new(table_name, "is_trigger"),
            collision_group: __sdk::__query_builder::Col::new(table_name, "collision_group"),
            collision_mask: __sdk::__query_builder::Col::new(table_name, "collision_mask"),
        }
    }
}

/// Indexed column accessor struct for the table `ColliderRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct ColliderRowIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<ColliderRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for ColliderRow {
    type IxCols = ColliderRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ColliderRowIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ColliderRow {}
