// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::collider_row_type::ColliderRow;
use super::collider_shape_kind_type::ColliderShapeKind;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `collider`.
///
/// Obtain a handle from the [`ColliderTableAccess::collider`] method on [`super::RemoteTables`],
/// like `ctx.db.collider()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.collider().on_insert(...)`.
pub struct ColliderTableHandle<'ctx> {
    imp: __sdk::TableHandle<ColliderRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `collider`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ColliderTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ColliderTableHandle`], which mediates access to the table `collider`.
    fn collider(&self) -> ColliderTableHandle<'_>;
}

impl ColliderTableAccess for super::RemoteTables {
    fn collider(&self) -> ColliderTableHandle<'_> {
        ColliderTableHandle {
            imp: self.imp.get_table::<ColliderRow>("collider"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ColliderInsertCallbackId(__sdk::CallbackId);
pub struct ColliderDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ColliderTableHandle<'ctx> {
    type Row = ColliderRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ColliderRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ColliderInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ColliderInsertCallbackId {
        ColliderInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ColliderInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ColliderDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ColliderDeleteCallbackId {
        ColliderDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ColliderDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ColliderUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ColliderTableHandle<'ctx> {
    type UpdateCallbackId = ColliderUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ColliderUpdateCallbackId {
        ColliderUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ColliderUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `collider`,
/// which allows point queries on the field of the same name
/// via the [`ColliderEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.collider().entity_id().find(...)`.
pub struct ColliderEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ColliderRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ColliderTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `collider`.
    pub fn entity_id(&self) -> ColliderEntityIdUnique<'ctx> {
        ColliderEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ColliderEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ColliderRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ColliderRow>("collider");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ColliderRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ColliderRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ColliderRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait colliderQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ColliderRow`.
    fn collider(&self) -> __sdk::__query_builder::Table<ColliderRow>;
}

impl colliderQueryTableAccess for __sdk::QueryTableAccessor {
    fn collider(&self) -> __sdk::__query_builder::Table<ColliderRow> {
        __sdk::__query_builder::Table::new("collider")
    }
}
