// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::color_rect_row_type::ColorRectRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `color_rect`.
///
/// Obtain a handle from the [`ColorRectTableAccess::color_rect`] method on [`super::RemoteTables`],
/// like `ctx.db.color_rect()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.color_rect().on_insert(...)`.
pub struct ColorRectTableHandle<'ctx> {
    imp: __sdk::TableHandle<ColorRectRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `color_rect`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ColorRectTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ColorRectTableHandle`], which mediates access to the table `color_rect`.
    fn color_rect(&self) -> ColorRectTableHandle<'_>;
}

impl ColorRectTableAccess for super::RemoteTables {
    fn color_rect(&self) -> ColorRectTableHandle<'_> {
        ColorRectTableHandle {
            imp: self.imp.get_table::<ColorRectRow>("color_rect"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ColorRectInsertCallbackId(__sdk::CallbackId);
pub struct ColorRectDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ColorRectTableHandle<'ctx> {
    type Row = ColorRectRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ColorRectRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ColorRectInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ColorRectInsertCallbackId {
        ColorRectInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ColorRectInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ColorRectDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ColorRectDeleteCallbackId {
        ColorRectDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ColorRectDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ColorRectUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ColorRectTableHandle<'ctx> {
    type UpdateCallbackId = ColorRectUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ColorRectUpdateCallbackId {
        ColorRectUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ColorRectUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `color_rect`,
/// which allows point queries on the field of the same name
/// via the [`ColorRectEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.color_rect().entity_id().find(...)`.
pub struct ColorRectEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ColorRectRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ColorRectTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `color_rect`.
    pub fn entity_id(&self) -> ColorRectEntityIdUnique<'ctx> {
        ColorRectEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ColorRectEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ColorRectRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ColorRectRow>("color_rect");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ColorRectRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ColorRectRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ColorRectRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait color_rectQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ColorRectRow`.
    fn color_rect(&self) -> __sdk::__query_builder::Table<ColorRectRow>;
}

impl color_rectQueryTableAccess for __sdk::QueryTableAccessor {
    fn color_rect(&self) -> __sdk::__query_builder::Table<ColorRectRow> {
        __sdk::__query_builder::Table::new("color_rect")
    }
}
