// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ColorRectRow {
    pub entity_id: u64,
    pub width: f32,
    pub height: f32,
    pub color_r: f32,
    pub color_g: f32,
    pub color_b: f32,
    pub color_a: f32,
    pub layer: i32,
}

impl __sdk::InModule for ColorRectRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ColorRectRow`.
///
/// Provides typed access to columns for query building.
pub struct ColorRectRowCols {
    pub entity_id: __sdk::__query_builder::Col<ColorRectRow, u64>,
    pub width: __sdk::__query_builder::Col<ColorRectRow, f32>,
    pub height: __sdk::__query_builder::Col<ColorRectRow, f32>,
    pub color_r: __sdk::__query_builder::Col<ColorRectRow, f32>,
    pub color_g: __sdk::__query_builder::Col<ColorRectRow, f32>,
    pub color_b: __sdk::__query_builder::Col<ColorRectRow, f32>,
    pub color_a: __sdk::__query_builder::Col<ColorRectRow, f32>,
    pub layer: __sdk::__query_builder::Col<ColorRectRow, i32>,
}

impl __sdk::__query_builder::HasCols for ColorRectRow {
    type Cols = ColorRectRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ColorRectRowCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            width: __sdk::__query_builder::Col::new(table_name, "width"),
            height: __sdk::__query_builder::Col::new(table_name, "height"),
            color_r: __sdk::__query_builder::Col::new(table_name, "color_r"),
            color_g: __sdk::__query_builder::Col::new(table_name, "color_g"),
            color_b: __sdk::__query_builder::Col::new(table_name, "color_b"),
            color_a: __sdk::__query_builder::Col::new(table_name, "color_a"),
            layer: __sdk::__query_builder::Col::new(table_name, "layer"),
        }
    }
}

/// Indexed column accessor struct for the table `ColorRectRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct ColorRectRowIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<ColorRectRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for ColorRectRow {
    type IxCols = ColorRectRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ColorRectRowIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ColorRectRow {}
