// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CombatEventRow {
    pub event_id: u64,
    pub tick: u64,
    pub attacker_entity_id: u64,
    pub defender_entity_id: u64,
    pub damage_dealt: f32,
    pub defender_health_remaining: f32,
    pub killed: bool,
}

impl __sdk::InModule for CombatEventRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CombatEventRow`.
///
/// Provides typed access to columns for query building.
pub struct CombatEventRowCols {
    pub event_id: __sdk::__query_builder::Col<CombatEventRow, u64>,
    pub tick: __sdk::__query_builder::Col<CombatEventRow, u64>,
    pub attacker_entity_id: __sdk::__query_builder::Col<CombatEventRow, u64>,
    pub defender_entity_id: __sdk::__query_builder::Col<CombatEventRow, u64>,
    pub damage_dealt: __sdk::__query_builder::Col<CombatEventRow, f32>,
    pub defender_health_remaining: __sdk::__query_builder::Col<CombatEventRow, f32>,
    pub killed: __sdk::__query_builder::Col<CombatEventRow, bool>,
}

impl __sdk::__query_builder::HasCols for CombatEventRow {
    type Cols = CombatEventRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CombatEventRowCols {
            event_id: __sdk::__query_builder::Col::new(table_name, "event_id"),
            tick: __sdk::__query_builder::Col::new(table_name, "tick"),
            attacker_entity_id: __sdk::__query_builder::Col::new(table_name, "attacker_entity_id"),
            defender_entity_id: __sdk::__query_builder::Col::new(table_name, "defender_entity_id"),
            damage_dealt: __sdk::__query_builder::Col::new(table_name, "damage_dealt"),
            defender_health_remaining: __sdk::__query_builder::Col::new(
                table_name,
                "defender_health_remaining",
            ),
            killed: __sdk::__query_builder::Col::new(table_name, "killed"),
        }
    }
}

/// Indexed column accessor struct for the table `CombatEventRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct CombatEventRowIxCols {
    pub event_id: __sdk::__query_builder::IxCol<CombatEventRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for CombatEventRow {
    type IxCols = CombatEventRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CombatEventRowIxCols {
            event_id: __sdk::__query_builder::IxCol::new(table_name, "event_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CombatEventRow {}
