// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::combat_event_row_type::CombatEventRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `combat_event`.
///
/// Obtain a handle from the [`CombatEventTableAccess::combat_event`] method on [`super::RemoteTables`],
/// like `ctx.db.combat_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.combat_event().on_insert(...)`.
pub struct CombatEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<CombatEventRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `combat_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CombatEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CombatEventTableHandle`], which mediates access to the table `combat_event`.
    fn combat_event(&self) -> CombatEventTableHandle<'_>;
}

impl CombatEventTableAccess for super::RemoteTables {
    fn combat_event(&self) -> CombatEventTableHandle<'_> {
        CombatEventTableHandle {
            imp: self.imp.get_table::<CombatEventRow>("combat_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CombatEventInsertCallbackId(__sdk::CallbackId);
pub struct CombatEventDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CombatEventTableHandle<'ctx> {
    type Row = CombatEventRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CombatEventRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CombatEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CombatEventInsertCallbackId {
        CombatEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CombatEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CombatEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CombatEventDeleteCallbackId {
        CombatEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CombatEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CombatEventUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CombatEventTableHandle<'ctx> {
    type UpdateCallbackId = CombatEventUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CombatEventUpdateCallbackId {
        CombatEventUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CombatEventUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `event_id` unique index on the table `combat_event`,
/// which allows point queries on the field of the same name
/// via the [`CombatEventEventIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.combat_event().event_id().find(...)`.
pub struct CombatEventEventIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CombatEventRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CombatEventTableHandle<'ctx> {
    /// Get a handle on the `event_id` unique index on the table `combat_event`.
    pub fn event_id(&self) -> CombatEventEventIdUnique<'ctx> {
        CombatEventEventIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("event_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CombatEventEventIdUnique<'ctx> {
    /// Find the subscribed row whose `event_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CombatEventRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CombatEventRow>("combat_event");
    _table.add_unique_constraint::<u64>("event_id", |row| &row.event_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CombatEventRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CombatEventRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CombatEventRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait combat_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CombatEventRow`.
    fn combat_event(&self) -> __sdk::__query_builder::Table<CombatEventRow>;
}

impl combat_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn combat_event(&self) -> __sdk::__query_builder::Table<CombatEventRow> {
        __sdk::__query_builder::Table::new("combat_event")
    }
}
