// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::agent_type_type::AgentType;
use super::connected_agent_row_type::ConnectedAgentRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `connected_agent`.
///
/// Obtain a handle from the [`ConnectedAgentTableAccess::connected_agent`] method on [`super::RemoteTables`],
/// like `ctx.db.connected_agent()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.connected_agent().on_insert(...)`.
pub struct ConnectedAgentTableHandle<'ctx> {
    imp: __sdk::TableHandle<ConnectedAgentRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `connected_agent`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ConnectedAgentTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ConnectedAgentTableHandle`], which mediates access to the table `connected_agent`.
    fn connected_agent(&self) -> ConnectedAgentTableHandle<'_>;
}

impl ConnectedAgentTableAccess for super::RemoteTables {
    fn connected_agent(&self) -> ConnectedAgentTableHandle<'_> {
        ConnectedAgentTableHandle {
            imp: self.imp.get_table::<ConnectedAgentRow>("connected_agent"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ConnectedAgentInsertCallbackId(__sdk::CallbackId);
pub struct ConnectedAgentDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ConnectedAgentTableHandle<'ctx> {
    type Row = ConnectedAgentRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ConnectedAgentRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ConnectedAgentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ConnectedAgentInsertCallbackId {
        ConnectedAgentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ConnectedAgentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ConnectedAgentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ConnectedAgentDeleteCallbackId {
        ConnectedAgentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ConnectedAgentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ConnectedAgentUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ConnectedAgentTableHandle<'ctx> {
    type UpdateCallbackId = ConnectedAgentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ConnectedAgentUpdateCallbackId {
        ConnectedAgentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ConnectedAgentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `identity` unique index on the table `connected_agent`,
/// which allows point queries on the field of the same name
/// via the [`ConnectedAgentIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.connected_agent().identity().find(...)`.
pub struct ConnectedAgentIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ConnectedAgentRow, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ConnectedAgentTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `connected_agent`.
    pub fn identity(&self) -> ConnectedAgentIdentityUnique<'ctx> {
        ConnectedAgentIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ConnectedAgentIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<ConnectedAgentRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ConnectedAgentRow>("connected_agent");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ConnectedAgentRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ConnectedAgentRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ConnectedAgentRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait connected_agentQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ConnectedAgentRow`.
    fn connected_agent(&self) -> __sdk::__query_builder::Table<ConnectedAgentRow>;
}

impl connected_agentQueryTableAccess for __sdk::QueryTableAccessor {
    fn connected_agent(&self) -> __sdk::__query_builder::Table<ConnectedAgentRow> {
        __sdk::__query_builder::Table::new("connected_agent")
    }
}
