// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::agent_type_type::AgentType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ConnectedAgentRow {
    pub identity: __sdk::Identity,
    pub entity_id: u64,
    pub agent_type: AgentType,
    pub display_name: String,
    pub connected_at: __sdk::Timestamp,
}

impl __sdk::InModule for ConnectedAgentRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ConnectedAgentRow`.
///
/// Provides typed access to columns for query building.
pub struct ConnectedAgentRowCols {
    pub identity: __sdk::__query_builder::Col<ConnectedAgentRow, __sdk::Identity>,
    pub entity_id: __sdk::__query_builder::Col<ConnectedAgentRow, u64>,
    pub agent_type: __sdk::__query_builder::Col<ConnectedAgentRow, AgentType>,
    pub display_name: __sdk::__query_builder::Col<ConnectedAgentRow, String>,
    pub connected_at: __sdk::__query_builder::Col<ConnectedAgentRow, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for ConnectedAgentRow {
    type Cols = ConnectedAgentRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ConnectedAgentRowCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            agent_type: __sdk::__query_builder::Col::new(table_name, "agent_type"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            connected_at: __sdk::__query_builder::Col::new(table_name, "connected_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ConnectedAgentRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct ConnectedAgentRowIxCols {
    pub identity: __sdk::__query_builder::IxCol<ConnectedAgentRow, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for ConnectedAgentRow {
    type IxCols = ConnectedAgentRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ConnectedAgentRowIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ConnectedAgentRow {}
