// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::agent_type_type::AgentType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ConnectAgentArgs {
    pub entity_id: u64,
    pub agent_type: AgentType,
    pub display_name: String,
}

impl From<ConnectAgentArgs> for super::Reducer {
    fn from(args: ConnectAgentArgs) -> Self {
        Self::ConnectAgent {
            entity_id: args.entity_id,
            agent_type: args.agent_type,
            display_name: args.display_name,
        }
    }
}

impl __sdk::InModule for ConnectAgentArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `connect_agent`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait connect_agent {
    /// Request that the remote module invoke the reducer `connect_agent` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`connect_agent:connect_agent_then`] to run a callback after the reducer completes.
    fn connect_agent(
        &self,
        entity_id: u64,
        agent_type: AgentType,
        display_name: String,
    ) -> __sdk::Result<()> {
        self.connect_agent_then(entity_id, agent_type, display_name, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `connect_agent` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn connect_agent_then(
        &self,
        entity_id: u64,
        agent_type: AgentType,
        display_name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl connect_agent for super::RemoteReducers {
    fn connect_agent_then(
        &self,
        entity_id: u64,
        agent_type: AgentType,
        display_name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ConnectAgentArgs {
                entity_id,
                agent_type,
                display_name,
            },
            callback,
        )
    }
}
