// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateMatchFromQueueArgs {
    pub desired_party_size: u32,
}

impl From<CreateMatchFromQueueArgs> for super::Reducer {
    fn from(args: CreateMatchFromQueueArgs) -> Self {
        Self::CreateMatchFromQueue {
            desired_party_size: args.desired_party_size,
        }
    }
}

impl __sdk::InModule for CreateMatchFromQueueArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_match_from_queue`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_match_from_queue {
    /// Request that the remote module invoke the reducer `create_match_from_queue` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_match_from_queue:create_match_from_queue_then`] to run a callback after the reducer completes.
    fn create_match_from_queue(&self, desired_party_size: u32) -> __sdk::Result<()> {
        self.create_match_from_queue_then(desired_party_size, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_match_from_queue` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_match_from_queue_then(
        &self,
        desired_party_size: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_match_from_queue for super::RemoteReducers {
    fn create_match_from_queue_then(
        &self,
        desired_party_size: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CreateMatchFromQueueArgs { desired_party_size }, callback)
    }
}
