// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateWorldArgs {
    pub seed: u64,
    pub width: f32,
    pub height: f32,
    pub tps: u32,
}

impl From<CreateWorldArgs> for super::Reducer {
    fn from(args: CreateWorldArgs) -> Self {
        Self::CreateWorld {
            seed: args.seed,
            width: args.width,
            height: args.height,
            tps: args.tps,
        }
    }
}

impl __sdk::InModule for CreateWorldArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_world`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_world {
    /// Request that the remote module invoke the reducer `create_world` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_world:create_world_then`] to run a callback after the reducer completes.
    fn create_world(&self, seed: u64, width: f32, height: f32, tps: u32) -> __sdk::Result<()> {
        self.create_world_then(seed, width, height, tps, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_world` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_world_then(
        &self,
        seed: u64,
        width: f32,
        height: f32,
        tps: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_world for super::RemoteReducers {
    fn create_world_then(
        &self,
        seed: u64,
        width: f32,
        height: f32,
        tps: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateWorldArgs {
                seed,
                width,
                height,
                tps,
            },
            callback,
        )
    }
}
