// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DestroyEntityArgs {
    pub entity_id: u64,
}

impl From<DestroyEntityArgs> for super::Reducer {
    fn from(args: DestroyEntityArgs) -> Self {
        Self::DestroyEntity {
            entity_id: args.entity_id,
        }
    }
}

impl __sdk::InModule for DestroyEntityArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `destroy_entity`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait destroy_entity {
    /// Request that the remote module invoke the reducer `destroy_entity` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`destroy_entity:destroy_entity_then`] to run a callback after the reducer completes.
    fn destroy_entity(&self, entity_id: u64) -> __sdk::Result<()> {
        self.destroy_entity_then(entity_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `destroy_entity` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn destroy_entity_then(
        &self,
        entity_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl destroy_entity for super::RemoteReducers {
    fn destroy_entity_then(
        &self,
        entity_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DestroyEntityArgs { entity_id }, callback)
    }
}
