// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::agent_type_type::AgentType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EntityRow {
    pub entity_id: u64,
    pub agent_type: Option<AgentType>,
    pub owner_identity: Option<__sdk::Identity>,
    pub alive: bool,
    pub created_tick: u64,
}

impl __sdk::InModule for EntityRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EntityRow`.
///
/// Provides typed access to columns for query building.
pub struct EntityRowCols {
    pub entity_id: __sdk::__query_builder::Col<EntityRow, u64>,
    pub agent_type: __sdk::__query_builder::Col<EntityRow, Option<AgentType>>,
    pub owner_identity: __sdk::__query_builder::Col<EntityRow, Option<__sdk::Identity>>,
    pub alive: __sdk::__query_builder::Col<EntityRow, bool>,
    pub created_tick: __sdk::__query_builder::Col<EntityRow, u64>,
}

impl __sdk::__query_builder::HasCols for EntityRow {
    type Cols = EntityRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EntityRowCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            agent_type: __sdk::__query_builder::Col::new(table_name, "agent_type"),
            owner_identity: __sdk::__query_builder::Col::new(table_name, "owner_identity"),
            alive: __sdk::__query_builder::Col::new(table_name, "alive"),
            created_tick: __sdk::__query_builder::Col::new(table_name, "created_tick"),
        }
    }
}

/// Indexed column accessor struct for the table `EntityRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct EntityRowIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<EntityRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for EntityRow {
    type IxCols = EntityRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EntityRowIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EntityRow {}
