// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::match_state_type::MatchState;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GameMatchRow {
    pub match_id: u64,
    pub created_tick: u64,
    pub max_players: u32,
    pub state: MatchState,
    pub started_tick: Option<u64>,
}

impl __sdk::InModule for GameMatchRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GameMatchRow`.
///
/// Provides typed access to columns for query building.
pub struct GameMatchRowCols {
    pub match_id: __sdk::__query_builder::Col<GameMatchRow, u64>,
    pub created_tick: __sdk::__query_builder::Col<GameMatchRow, u64>,
    pub max_players: __sdk::__query_builder::Col<GameMatchRow, u32>,
    pub state: __sdk::__query_builder::Col<GameMatchRow, MatchState>,
    pub started_tick: __sdk::__query_builder::Col<GameMatchRow, Option<u64>>,
}

impl __sdk::__query_builder::HasCols for GameMatchRow {
    type Cols = GameMatchRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GameMatchRowCols {
            match_id: __sdk::__query_builder::Col::new(table_name, "match_id"),
            created_tick: __sdk::__query_builder::Col::new(table_name, "created_tick"),
            max_players: __sdk::__query_builder::Col::new(table_name, "max_players"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
            started_tick: __sdk::__query_builder::Col::new(table_name, "started_tick"),
        }
    }
}

/// Indexed column accessor struct for the table `GameMatchRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct GameMatchRowIxCols {
    pub match_id: __sdk::__query_builder::IxCol<GameMatchRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for GameMatchRow {
    type IxCols = GameMatchRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GameMatchRowIxCols {
            match_id: __sdk::__query_builder::IxCol::new(table_name, "match_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GameMatchRow {}
