// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::game_match_row_type::GameMatchRow;
use super::match_state_type::MatchState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_match`.
///
/// Obtain a handle from the [`GameMatchTableAccess::game_match`] method on [`super::RemoteTables`],
/// like `ctx.db.game_match()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_match().on_insert(...)`.
pub struct GameMatchTableHandle<'ctx> {
    imp: __sdk::TableHandle<GameMatchRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_match`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameMatchTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameMatchTableHandle`], which mediates access to the table `game_match`.
    fn game_match(&self) -> GameMatchTableHandle<'_>;
}

impl GameMatchTableAccess for super::RemoteTables {
    fn game_match(&self) -> GameMatchTableHandle<'_> {
        GameMatchTableHandle {
            imp: self.imp.get_table::<GameMatchRow>("game_match"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameMatchInsertCallbackId(__sdk::CallbackId);
pub struct GameMatchDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GameMatchTableHandle<'ctx> {
    type Row = GameMatchRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GameMatchRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameMatchInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameMatchInsertCallbackId {
        GameMatchInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameMatchInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameMatchDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameMatchDeleteCallbackId {
        GameMatchDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameMatchDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameMatchUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameMatchTableHandle<'ctx> {
    type UpdateCallbackId = GameMatchUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameMatchUpdateCallbackId {
        GameMatchUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameMatchUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `match_id` unique index on the table `game_match`,
/// which allows point queries on the field of the same name
/// via the [`GameMatchMatchIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_match().match_id().find(...)`.
pub struct GameMatchMatchIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GameMatchRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameMatchTableHandle<'ctx> {
    /// Get a handle on the `match_id` unique index on the table `game_match`.
    pub fn match_id(&self) -> GameMatchMatchIdUnique<'ctx> {
        GameMatchMatchIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("match_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameMatchMatchIdUnique<'ctx> {
    /// Find the subscribed row whose `match_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<GameMatchRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GameMatchRow>("game_match");
    _table.add_unique_constraint::<u64>("match_id", |row| &row.match_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GameMatchRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GameMatchRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GameMatchRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_matchQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GameMatchRow`.
    fn game_match(&self) -> __sdk::__query_builder::Table<GameMatchRow>;
}

impl game_matchQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_match(&self) -> __sdk::__query_builder::Table<GameMatchRow> {
        __sdk::__query_builder::Table::new("game_match")
    }
}
