// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct HealthRow {
    pub entity_id: u64,
    pub current: f32,
    pub max_hp: f32,
    pub armor: f32,
    pub invulnerable: bool,
}

impl __sdk::InModule for HealthRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `HealthRow`.
///
/// Provides typed access to columns for query building.
pub struct HealthRowCols {
    pub entity_id: __sdk::__query_builder::Col<HealthRow, u64>,
    pub current: __sdk::__query_builder::Col<HealthRow, f32>,
    pub max_hp: __sdk::__query_builder::Col<HealthRow, f32>,
    pub armor: __sdk::__query_builder::Col<HealthRow, f32>,
    pub invulnerable: __sdk::__query_builder::Col<HealthRow, bool>,
}

impl __sdk::__query_builder::HasCols for HealthRow {
    type Cols = HealthRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        HealthRowCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            current: __sdk::__query_builder::Col::new(table_name, "current"),
            max_hp: __sdk::__query_builder::Col::new(table_name, "max_hp"),
            armor: __sdk::__query_builder::Col::new(table_name, "armor"),
            invulnerable: __sdk::__query_builder::Col::new(table_name, "invulnerable"),
        }
    }
}

/// Indexed column accessor struct for the table `HealthRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct HealthRowIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<HealthRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for HealthRow {
    type IxCols = HealthRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        HealthRowIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for HealthRow {}
