// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LabelRow {
    pub entity_id: u64,
    pub name: String,
    pub team_id: u8,
}

impl __sdk::InModule for LabelRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LabelRow`.
///
/// Provides typed access to columns for query building.
pub struct LabelRowCols {
    pub entity_id: __sdk::__query_builder::Col<LabelRow, u64>,
    pub name: __sdk::__query_builder::Col<LabelRow, String>,
    pub team_id: __sdk::__query_builder::Col<LabelRow, u8>,
}

impl __sdk::__query_builder::HasCols for LabelRow {
    type Cols = LabelRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LabelRowCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            team_id: __sdk::__query_builder::Col::new(table_name, "team_id"),
        }
    }
}

/// Indexed column accessor struct for the table `LabelRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct LabelRowIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<LabelRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for LabelRow {
    type IxCols = LabelRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LabelRowIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LabelRow {}
