// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LobbyMemberRow {
    pub membership_id: u64,
    pub lobby_id: u64,
    pub identity: __sdk::Identity,
    pub entity_id: u64,
    pub joined_at_tick: u64,
    pub is_ready: bool,
}

impl __sdk::InModule for LobbyMemberRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LobbyMemberRow`.
///
/// Provides typed access to columns for query building.
pub struct LobbyMemberRowCols {
    pub membership_id: __sdk::__query_builder::Col<LobbyMemberRow, u64>,
    pub lobby_id: __sdk::__query_builder::Col<LobbyMemberRow, u64>,
    pub identity: __sdk::__query_builder::Col<LobbyMemberRow, __sdk::Identity>,
    pub entity_id: __sdk::__query_builder::Col<LobbyMemberRow, u64>,
    pub joined_at_tick: __sdk::__query_builder::Col<LobbyMemberRow, u64>,
    pub is_ready: __sdk::__query_builder::Col<LobbyMemberRow, bool>,
}

impl __sdk::__query_builder::HasCols for LobbyMemberRow {
    type Cols = LobbyMemberRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LobbyMemberRowCols {
            membership_id: __sdk::__query_builder::Col::new(table_name, "membership_id"),
            lobby_id: __sdk::__query_builder::Col::new(table_name, "lobby_id"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            joined_at_tick: __sdk::__query_builder::Col::new(table_name, "joined_at_tick"),
            is_ready: __sdk::__query_builder::Col::new(table_name, "is_ready"),
        }
    }
}

/// Indexed column accessor struct for the table `LobbyMemberRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct LobbyMemberRowIxCols {
    pub membership_id: __sdk::__query_builder::IxCol<LobbyMemberRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for LobbyMemberRow {
    type IxCols = LobbyMemberRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LobbyMemberRowIxCols {
            membership_id: __sdk::__query_builder::IxCol::new(table_name, "membership_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LobbyMemberRow {}
