// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::lobby_member_row_type::LobbyMemberRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `lobby_member`.
///
/// Obtain a handle from the [`LobbyMemberTableAccess::lobby_member`] method on [`super::RemoteTables`],
/// like `ctx.db.lobby_member()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.lobby_member().on_insert(...)`.
pub struct LobbyMemberTableHandle<'ctx> {
    imp: __sdk::TableHandle<LobbyMemberRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `lobby_member`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LobbyMemberTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LobbyMemberTableHandle`], which mediates access to the table `lobby_member`.
    fn lobby_member(&self) -> LobbyMemberTableHandle<'_>;
}

impl LobbyMemberTableAccess for super::RemoteTables {
    fn lobby_member(&self) -> LobbyMemberTableHandle<'_> {
        LobbyMemberTableHandle {
            imp: self.imp.get_table::<LobbyMemberRow>("lobby_member"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LobbyMemberInsertCallbackId(__sdk::CallbackId);
pub struct LobbyMemberDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LobbyMemberTableHandle<'ctx> {
    type Row = LobbyMemberRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LobbyMemberRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LobbyMemberInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LobbyMemberInsertCallbackId {
        LobbyMemberInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LobbyMemberInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LobbyMemberDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LobbyMemberDeleteCallbackId {
        LobbyMemberDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LobbyMemberDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct LobbyMemberUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LobbyMemberTableHandle<'ctx> {
    type UpdateCallbackId = LobbyMemberUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LobbyMemberUpdateCallbackId {
        LobbyMemberUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LobbyMemberUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `membership_id` unique index on the table `lobby_member`,
/// which allows point queries on the field of the same name
/// via the [`LobbyMemberMembershipIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.lobby_member().membership_id().find(...)`.
pub struct LobbyMemberMembershipIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LobbyMemberRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LobbyMemberTableHandle<'ctx> {
    /// Get a handle on the `membership_id` unique index on the table `lobby_member`.
    pub fn membership_id(&self) -> LobbyMemberMembershipIdUnique<'ctx> {
        LobbyMemberMembershipIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("membership_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LobbyMemberMembershipIdUnique<'ctx> {
    /// Find the subscribed row whose `membership_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<LobbyMemberRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LobbyMemberRow>("lobby_member");
    _table.add_unique_constraint::<u64>("membership_id", |row| &row.membership_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LobbyMemberRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LobbyMemberRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LobbyMemberRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait lobby_memberQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LobbyMemberRow`.
    fn lobby_member(&self) -> __sdk::__query_builder::Table<LobbyMemberRow>;
}

impl lobby_memberQueryTableAccess for __sdk::QueryTableAccessor {
    fn lobby_member(&self) -> __sdk::__query_builder::Table<LobbyMemberRow> {
        __sdk::__query_builder::Table::new("lobby_member")
    }
}
