// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LobbyRow {
    pub lobby_id: u64,
    pub name: String,
    pub host_identity: __sdk::Identity,
    pub host_entity_id: u64,
    pub max_players: u32,
    pub is_private: bool,
    pub created_at: __sdk::Timestamp,
    pub started: bool,
}

impl __sdk::InModule for LobbyRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LobbyRow`.
///
/// Provides typed access to columns for query building.
pub struct LobbyRowCols {
    pub lobby_id: __sdk::__query_builder::Col<LobbyRow, u64>,
    pub name: __sdk::__query_builder::Col<LobbyRow, String>,
    pub host_identity: __sdk::__query_builder::Col<LobbyRow, __sdk::Identity>,
    pub host_entity_id: __sdk::__query_builder::Col<LobbyRow, u64>,
    pub max_players: __sdk::__query_builder::Col<LobbyRow, u32>,
    pub is_private: __sdk::__query_builder::Col<LobbyRow, bool>,
    pub created_at: __sdk::__query_builder::Col<LobbyRow, __sdk::Timestamp>,
    pub started: __sdk::__query_builder::Col<LobbyRow, bool>,
}

impl __sdk::__query_builder::HasCols for LobbyRow {
    type Cols = LobbyRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LobbyRowCols {
            lobby_id: __sdk::__query_builder::Col::new(table_name, "lobby_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            host_identity: __sdk::__query_builder::Col::new(table_name, "host_identity"),
            host_entity_id: __sdk::__query_builder::Col::new(table_name, "host_entity_id"),
            max_players: __sdk::__query_builder::Col::new(table_name, "max_players"),
            is_private: __sdk::__query_builder::Col::new(table_name, "is_private"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            started: __sdk::__query_builder::Col::new(table_name, "started"),
        }
    }
}

/// Indexed column accessor struct for the table `LobbyRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct LobbyRowIxCols {
    pub lobby_id: __sdk::__query_builder::IxCol<LobbyRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for LobbyRow {
    type IxCols = LobbyRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LobbyRowIxCols {
            lobby_id: __sdk::__query_builder::IxCol::new(table_name, "lobby_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LobbyRow {}
