// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MatchQueueRow {
    pub queue_id: u64,
    pub identity: __sdk::Identity,
    pub entity_id: u64,
    pub desired_party_size: u32,
    pub queued_at_tick: u64,
}

impl __sdk::InModule for MatchQueueRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MatchQueueRow`.
///
/// Provides typed access to columns for query building.
pub struct MatchQueueRowCols {
    pub queue_id: __sdk::__query_builder::Col<MatchQueueRow, u64>,
    pub identity: __sdk::__query_builder::Col<MatchQueueRow, __sdk::Identity>,
    pub entity_id: __sdk::__query_builder::Col<MatchQueueRow, u64>,
    pub desired_party_size: __sdk::__query_builder::Col<MatchQueueRow, u32>,
    pub queued_at_tick: __sdk::__query_builder::Col<MatchQueueRow, u64>,
}

impl __sdk::__query_builder::HasCols for MatchQueueRow {
    type Cols = MatchQueueRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MatchQueueRowCols {
            queue_id: __sdk::__query_builder::Col::new(table_name, "queue_id"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            desired_party_size: __sdk::__query_builder::Col::new(table_name, "desired_party_size"),
            queued_at_tick: __sdk::__query_builder::Col::new(table_name, "queued_at_tick"),
        }
    }
}

/// Indexed column accessor struct for the table `MatchQueueRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct MatchQueueRowIxCols {
    pub queue_id: __sdk::__query_builder::IxCol<MatchQueueRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for MatchQueueRow {
    type IxCols = MatchQueueRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MatchQueueRowIxCols {
            queue_id: __sdk::__query_builder::IxCol::new(table_name, "queue_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MatchQueueRow {}
