// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MatchParticipantRow {
    pub participant_id: u64,
    pub match_id: u64,
    pub identity: __sdk::Identity,
    pub entity_id: u64,
    pub team_id: u8,
    pub joined_at_tick: u64,
}

impl __sdk::InModule for MatchParticipantRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MatchParticipantRow`.
///
/// Provides typed access to columns for query building.
pub struct MatchParticipantRowCols {
    pub participant_id: __sdk::__query_builder::Col<MatchParticipantRow, u64>,
    pub match_id: __sdk::__query_builder::Col<MatchParticipantRow, u64>,
    pub identity: __sdk::__query_builder::Col<MatchParticipantRow, __sdk::Identity>,
    pub entity_id: __sdk::__query_builder::Col<MatchParticipantRow, u64>,
    pub team_id: __sdk::__query_builder::Col<MatchParticipantRow, u8>,
    pub joined_at_tick: __sdk::__query_builder::Col<MatchParticipantRow, u64>,
}

impl __sdk::__query_builder::HasCols for MatchParticipantRow {
    type Cols = MatchParticipantRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MatchParticipantRowCols {
            participant_id: __sdk::__query_builder::Col::new(table_name, "participant_id"),
            match_id: __sdk::__query_builder::Col::new(table_name, "match_id"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            team_id: __sdk::__query_builder::Col::new(table_name, "team_id"),
            joined_at_tick: __sdk::__query_builder::Col::new(table_name, "joined_at_tick"),
        }
    }
}

/// Indexed column accessor struct for the table `MatchParticipantRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct MatchParticipantRowIxCols {
    pub participant_id: __sdk::__query_builder::IxCol<MatchParticipantRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for MatchParticipantRow {
    type IxCols = MatchParticipantRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MatchParticipantRowIxCols {
            participant_id: __sdk::__query_builder::IxCol::new(table_name, "participant_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MatchParticipantRow {}
