// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::match_participant_row_type::MatchParticipantRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `match_participant`.
///
/// Obtain a handle from the [`MatchParticipantTableAccess::match_participant`] method on [`super::RemoteTables`],
/// like `ctx.db.match_participant()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.match_participant().on_insert(...)`.
pub struct MatchParticipantTableHandle<'ctx> {
    imp: __sdk::TableHandle<MatchParticipantRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `match_participant`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MatchParticipantTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MatchParticipantTableHandle`], which mediates access to the table `match_participant`.
    fn match_participant(&self) -> MatchParticipantTableHandle<'_>;
}

impl MatchParticipantTableAccess for super::RemoteTables {
    fn match_participant(&self) -> MatchParticipantTableHandle<'_> {
        MatchParticipantTableHandle {
            imp: self
                .imp
                .get_table::<MatchParticipantRow>("match_participant"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MatchParticipantInsertCallbackId(__sdk::CallbackId);
pub struct MatchParticipantDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MatchParticipantTableHandle<'ctx> {
    type Row = MatchParticipantRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchParticipantRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MatchParticipantInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchParticipantInsertCallbackId {
        MatchParticipantInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MatchParticipantInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MatchParticipantDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchParticipantDeleteCallbackId {
        MatchParticipantDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MatchParticipantDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MatchParticipantUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MatchParticipantTableHandle<'ctx> {
    type UpdateCallbackId = MatchParticipantUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MatchParticipantUpdateCallbackId {
        MatchParticipantUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MatchParticipantUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `participant_id` unique index on the table `match_participant`,
/// which allows point queries on the field of the same name
/// via the [`MatchParticipantParticipantIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.match_participant().participant_id().find(...)`.
pub struct MatchParticipantParticipantIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MatchParticipantRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MatchParticipantTableHandle<'ctx> {
    /// Get a handle on the `participant_id` unique index on the table `match_participant`.
    pub fn participant_id(&self) -> MatchParticipantParticipantIdUnique<'ctx> {
        MatchParticipantParticipantIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("participant_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MatchParticipantParticipantIdUnique<'ctx> {
    /// Find the subscribed row whose `participant_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MatchParticipantRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MatchParticipantRow>("match_participant");
    _table.add_unique_constraint::<u64>("participant_id", |row| &row.participant_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MatchParticipantRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MatchParticipantRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MatchParticipantRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait match_participantQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MatchParticipantRow`.
    fn match_participant(&self) -> __sdk::__query_builder::Table<MatchParticipantRow>;
}

impl match_participantQueryTableAccess for __sdk::QueryTableAccessor {
    fn match_participant(&self) -> __sdk::__query_builder::Table<MatchParticipantRow> {
        __sdk::__query_builder::Table::new("match_participant")
    }
}
