// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::match_queue_row_type::MatchQueueRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `match_queue`.
///
/// Obtain a handle from the [`MatchQueueTableAccess::match_queue`] method on [`super::RemoteTables`],
/// like `ctx.db.match_queue()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.match_queue().on_insert(...)`.
pub struct MatchQueueTableHandle<'ctx> {
    imp: __sdk::TableHandle<MatchQueueRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `match_queue`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MatchQueueTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MatchQueueTableHandle`], which mediates access to the table `match_queue`.
    fn match_queue(&self) -> MatchQueueTableHandle<'_>;
}

impl MatchQueueTableAccess for super::RemoteTables {
    fn match_queue(&self) -> MatchQueueTableHandle<'_> {
        MatchQueueTableHandle {
            imp: self.imp.get_table::<MatchQueueRow>("match_queue"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MatchQueueInsertCallbackId(__sdk::CallbackId);
pub struct MatchQueueDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MatchQueueTableHandle<'ctx> {
    type Row = MatchQueueRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchQueueRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MatchQueueInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchQueueInsertCallbackId {
        MatchQueueInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MatchQueueInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MatchQueueDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchQueueDeleteCallbackId {
        MatchQueueDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MatchQueueDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MatchQueueUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MatchQueueTableHandle<'ctx> {
    type UpdateCallbackId = MatchQueueUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MatchQueueUpdateCallbackId {
        MatchQueueUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MatchQueueUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `queue_id` unique index on the table `match_queue`,
/// which allows point queries on the field of the same name
/// via the [`MatchQueueQueueIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.match_queue().queue_id().find(...)`.
pub struct MatchQueueQueueIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MatchQueueRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MatchQueueTableHandle<'ctx> {
    /// Get a handle on the `queue_id` unique index on the table `match_queue`.
    pub fn queue_id(&self) -> MatchQueueQueueIdUnique<'ctx> {
        MatchQueueQueueIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("queue_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MatchQueueQueueIdUnique<'ctx> {
    /// Find the subscribed row whose `queue_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MatchQueueRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MatchQueueRow>("match_queue");
    _table.add_unique_constraint::<u64>("queue_id", |row| &row.queue_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MatchQueueRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MatchQueueRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MatchQueueRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait match_queueQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MatchQueueRow`.
    fn match_queue(&self) -> __sdk::__query_builder::Table<MatchQueueRow>;
}

impl match_queueQueryTableAccess for __sdk::QueryTableAccessor {
    fn match_queue(&self) -> __sdk::__query_builder::Table<MatchQueueRow> {
        __sdk::__query_builder::Table::new("match_queue")
    }
}
