// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.4 (commit 8b63d6398ae59c11ebb3af5935da75942ace472c).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod ability_target_kind_type;
pub mod action_kind_type;
pub mod action_submission_row_type;
pub mod action_submission_table;
pub mod agent_constraints_row_type;
pub mod agent_constraints_table;
pub mod agent_telemetry_tick_row_type;
pub mod agent_telemetry_tick_table;
pub mod agent_tick_rollup_row_type;
pub mod agent_tick_rollup_table;
pub mod agent_tool_call_event_row_type;
pub mod agent_tool_call_event_table;
pub mod agent_type_type;
pub mod body_kind_type;
pub mod collider_row_type;
pub mod collider_shape_kind_type;
pub mod collider_table;
pub mod color_rect_row_type;
pub mod color_rect_table;
pub mod combat_event_row_type;
pub mod combat_event_table;
pub mod connect_agent_reducer;
pub mod connected_agent_row_type;
pub mod connected_agent_table;
pub mod create_lobby_reducer;
pub mod create_match_from_queue_reducer;
pub mod create_world_reducer;
pub mod destroy_entity_reducer;
pub mod entity_row_type;
pub mod entity_table;
pub mod execute_tick_reducer;
pub mod game_match_row_type;
pub mod game_match_table;
pub mod health_row_type;
pub mod health_table;
pub mod join_lobby_reducer;
pub mod join_match_queue_reducer;
pub mod label_row_type;
pub mod label_table;
pub mod leave_lobby_reducer;
pub mod leave_match_queue_reducer;
pub mod lobby_member_row_type;
pub mod lobby_member_table;
pub mod lobby_row_type;
pub mod lobby_table;
pub mod match_participant_row_type;
pub mod match_participant_table;
pub mod match_queue_row_type;
pub mod match_queue_table;
pub mod match_state_type;
pub mod movement_row_type;
pub mod movement_table;
pub mod observation_event_row_type;
pub mod observation_event_table;
pub mod perception_row_type;
pub mod perception_table;
pub mod publish_remote_topology_document_reducer;
pub mod remote_topology_document_row_type;
pub mod remote_topology_document_table;
pub mod rigid_body_row_type;
pub mod rigid_body_table;
pub mod script_row_type;
pub mod script_table;
pub mod set_lobby_ready_reducer;
pub mod set_paused_reducer;
pub mod spawn_entity_full_reducer;
pub mod spawn_entity_reducer;
pub mod speak_volume_type;
pub mod speech_event_row_type;
pub mod speech_event_table;
pub mod sprite_row_type;
pub mod sprite_table;
pub mod start_lobby_reducer;
pub mod submit_action_reducer;
pub mod transform_row_type;
pub mod transform_table;
pub mod velocity_row_type;
pub mod velocity_table;
pub mod world_event_kind_type;
pub mod world_event_row_type;
pub mod world_event_table;
pub mod world_state_row_type;
pub mod world_state_table;

pub use ability_target_kind_type::AbilityTargetKind;
pub use action_kind_type::ActionKind;
pub use action_submission_row_type::ActionSubmissionRow;
pub use action_submission_table::*;
pub use agent_constraints_row_type::AgentConstraintsRow;
pub use agent_constraints_table::*;
pub use agent_telemetry_tick_row_type::AgentTelemetryTickRow;
pub use agent_telemetry_tick_table::*;
pub use agent_tick_rollup_row_type::AgentTickRollupRow;
pub use agent_tick_rollup_table::*;
pub use agent_tool_call_event_row_type::AgentToolCallEventRow;
pub use agent_tool_call_event_table::*;
pub use agent_type_type::AgentType;
pub use body_kind_type::BodyKind;
pub use collider_row_type::ColliderRow;
pub use collider_shape_kind_type::ColliderShapeKind;
pub use collider_table::*;
pub use color_rect_row_type::ColorRectRow;
pub use color_rect_table::*;
pub use combat_event_row_type::CombatEventRow;
pub use combat_event_table::*;
pub use connect_agent_reducer::connect_agent;
pub use connected_agent_row_type::ConnectedAgentRow;
pub use connected_agent_table::*;
pub use create_lobby_reducer::create_lobby;
pub use create_match_from_queue_reducer::create_match_from_queue;
pub use create_world_reducer::create_world;
pub use destroy_entity_reducer::destroy_entity;
pub use entity_row_type::EntityRow;
pub use entity_table::*;
pub use execute_tick_reducer::execute_tick;
pub use game_match_row_type::GameMatchRow;
pub use game_match_table::*;
pub use health_row_type::HealthRow;
pub use health_table::*;
pub use join_lobby_reducer::join_lobby;
pub use join_match_queue_reducer::join_match_queue;
pub use label_row_type::LabelRow;
pub use label_table::*;
pub use leave_lobby_reducer::leave_lobby;
pub use leave_match_queue_reducer::leave_match_queue;
pub use lobby_member_row_type::LobbyMemberRow;
pub use lobby_member_table::*;
pub use lobby_row_type::LobbyRow;
pub use lobby_table::*;
pub use match_participant_row_type::MatchParticipantRow;
pub use match_participant_table::*;
pub use match_queue_row_type::MatchQueueRow;
pub use match_queue_table::*;
pub use match_state_type::MatchState;
pub use movement_row_type::MovementRow;
pub use movement_table::*;
pub use observation_event_row_type::ObservationEventRow;
pub use observation_event_table::*;
pub use perception_row_type::PerceptionRow;
pub use perception_table::*;
pub use publish_remote_topology_document_reducer::publish_remote_topology_document;
pub use remote_topology_document_row_type::RemoteTopologyDocumentRow;
pub use remote_topology_document_table::*;
pub use rigid_body_row_type::RigidBodyRow;
pub use rigid_body_table::*;
pub use script_row_type::ScriptRow;
pub use script_table::*;
pub use set_lobby_ready_reducer::set_lobby_ready;
pub use set_paused_reducer::set_paused;
pub use spawn_entity_full_reducer::spawn_entity_full;
pub use spawn_entity_reducer::spawn_entity;
pub use speak_volume_type::SpeakVolume;
pub use speech_event_row_type::SpeechEventRow;
pub use speech_event_table::*;
pub use sprite_row_type::SpriteRow;
pub use sprite_table::*;
pub use start_lobby_reducer::start_lobby;
pub use submit_action_reducer::submit_action;
pub use transform_row_type::TransformRow;
pub use transform_table::*;
pub use velocity_row_type::VelocityRow;
pub use velocity_table::*;
pub use world_event_kind_type::WorldEventKind;
pub use world_event_row_type::WorldEventRow;
pub use world_event_table::*;
pub use world_state_row_type::WorldStateRow;
pub use world_state_table::*;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    ConnectAgent {
        entity_id: u64,
        agent_type: AgentType,
        display_name: String,
    },
    CreateLobby {
        name: String,
        host_entity_id: u64,
        max_players: u32,
        is_private: bool,
    },
    CreateMatchFromQueue {
        desired_party_size: u32,
    },
    CreateWorld {
        seed: u64,
        width: f32,
        height: f32,
        tps: u32,
    },
    DestroyEntity {
        entity_id: u64,
    },
    ExecuteTick,
    JoinLobby {
        lobby_id: u64,
        entity_id: u64,
    },
    JoinMatchQueue {
        entity_id: u64,
        desired_party_size: u32,
    },
    LeaveLobby,
    LeaveMatchQueue,
    PublishRemoteTopologyDocument {
        topology_json: String,
    },
    SetLobbyReady {
        lobby_id: u64,
        is_ready: bool,
    },
    SetPaused {
        paused: bool,
    },
    SpawnEntity {
        pos_x: f32,
        pos_y: f32,
        agent_type: Option<AgentType>,
    },
    SpawnEntityFull {
        pos_x: f32,
        pos_y: f32,
        agent_type: Option<AgentType>,
        rect_width: f32,
        rect_height: f32,
        color_r: f32,
        color_g: f32,
        color_b: f32,
        color_a: f32,
        label_name: String,
        team_id: u8,
        max_hp: f32,
        vision_range: f32,
        vision_fov: f32,
        hearing_range: f32,
    },
    StartLobby {
        lobby_id: u64,
    },
    SubmitAction {
        entity_id: u64,
        action_kind: ActionKind,
        direction_x: Option<f32>,
        direction_y: Option<f32>,
        angle: Option<f32>,
        target_x: Option<f32>,
        target_y: Option<f32>,
        target_entity_id: Option<u64>,
        ability_slot: Option<u8>,
        ability_target_kind: Option<AbilityTargetKind>,
        message: Option<String>,
        volume: Option<SpeakVolume>,
        signal_type: Option<String>,
        signal_data: Option<String>,
        prefab: Option<String>,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::ConnectAgent { .. } => "connect_agent",
            Reducer::CreateLobby { .. } => "create_lobby",
            Reducer::CreateMatchFromQueue { .. } => "create_match_from_queue",
            Reducer::CreateWorld { .. } => "create_world",
            Reducer::DestroyEntity { .. } => "destroy_entity",
            Reducer::ExecuteTick => "execute_tick",
            Reducer::JoinLobby { .. } => "join_lobby",
            Reducer::JoinMatchQueue { .. } => "join_match_queue",
            Reducer::LeaveLobby => "leave_lobby",
            Reducer::LeaveMatchQueue => "leave_match_queue",
            Reducer::PublishRemoteTopologyDocument { .. } => "publish_remote_topology_document",
            Reducer::SetLobbyReady { .. } => "set_lobby_ready",
            Reducer::SetPaused { .. } => "set_paused",
            Reducer::SpawnEntity { .. } => "spawn_entity",
            Reducer::SpawnEntityFull { .. } => "spawn_entity_full",
            Reducer::StartLobby { .. } => "start_lobby",
            Reducer::SubmitAction { .. } => "submit_action",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::ConnectAgent {
                entity_id,
                agent_type,
                display_name,
            } => __sats::bsatn::to_vec(&connect_agent_reducer::ConnectAgentArgs {
                entity_id: entity_id.clone(),
                agent_type: agent_type.clone(),
                display_name: display_name.clone(),
            }),
            Reducer::CreateLobby {
                name,
                host_entity_id,
                max_players,
                is_private,
            } => __sats::bsatn::to_vec(&create_lobby_reducer::CreateLobbyArgs {
                name: name.clone(),
                host_entity_id: host_entity_id.clone(),
                max_players: max_players.clone(),
                is_private: is_private.clone(),
            }),
            Reducer::CreateMatchFromQueue { desired_party_size } => {
                __sats::bsatn::to_vec(&create_match_from_queue_reducer::CreateMatchFromQueueArgs {
                    desired_party_size: desired_party_size.clone(),
                })
            }
            Reducer::CreateWorld {
                seed,
                width,
                height,
                tps,
            } => __sats::bsatn::to_vec(&create_world_reducer::CreateWorldArgs {
                seed: seed.clone(),
                width: width.clone(),
                height: height.clone(),
                tps: tps.clone(),
            }),
            Reducer::DestroyEntity { entity_id } => {
                __sats::bsatn::to_vec(&destroy_entity_reducer::DestroyEntityArgs {
                    entity_id: entity_id.clone(),
                })
            }
            Reducer::ExecuteTick => {
                __sats::bsatn::to_vec(&execute_tick_reducer::ExecuteTickArgs {})
            }
            Reducer::JoinLobby {
                lobby_id,
                entity_id,
            } => __sats::bsatn::to_vec(&join_lobby_reducer::JoinLobbyArgs {
                lobby_id: lobby_id.clone(),
                entity_id: entity_id.clone(),
            }),
            Reducer::JoinMatchQueue {
                entity_id,
                desired_party_size,
            } => __sats::bsatn::to_vec(&join_match_queue_reducer::JoinMatchQueueArgs {
                entity_id: entity_id.clone(),
                desired_party_size: desired_party_size.clone(),
            }),
            Reducer::LeaveLobby => __sats::bsatn::to_vec(&leave_lobby_reducer::LeaveLobbyArgs {}),
            Reducer::LeaveMatchQueue => {
                __sats::bsatn::to_vec(&leave_match_queue_reducer::LeaveMatchQueueArgs {})
            }
            Reducer::PublishRemoteTopologyDocument { topology_json } => __sats::bsatn::to_vec(
                &publish_remote_topology_document_reducer::PublishRemoteTopologyDocumentArgs {
                    topology_json: topology_json.clone(),
                },
            ),
            Reducer::SetLobbyReady { lobby_id, is_ready } => {
                __sats::bsatn::to_vec(&set_lobby_ready_reducer::SetLobbyReadyArgs {
                    lobby_id: lobby_id.clone(),
                    is_ready: is_ready.clone(),
                })
            }
            Reducer::SetPaused { paused } => {
                __sats::bsatn::to_vec(&set_paused_reducer::SetPausedArgs {
                    paused: paused.clone(),
                })
            }
            Reducer::SpawnEntity {
                pos_x,
                pos_y,
                agent_type,
            } => __sats::bsatn::to_vec(&spawn_entity_reducer::SpawnEntityArgs {
                pos_x: pos_x.clone(),
                pos_y: pos_y.clone(),
                agent_type: agent_type.clone(),
            }),
            Reducer::SpawnEntityFull {
                pos_x,
                pos_y,
                agent_type,
                rect_width,
                rect_height,
                color_r,
                color_g,
                color_b,
                color_a,
                label_name,
                team_id,
                max_hp,
                vision_range,
                vision_fov,
                hearing_range,
            } => __sats::bsatn::to_vec(&spawn_entity_full_reducer::SpawnEntityFullArgs {
                pos_x: pos_x.clone(),
                pos_y: pos_y.clone(),
                agent_type: agent_type.clone(),
                rect_width: rect_width.clone(),
                rect_height: rect_height.clone(),
                color_r: color_r.clone(),
                color_g: color_g.clone(),
                color_b: color_b.clone(),
                color_a: color_a.clone(),
                label_name: label_name.clone(),
                team_id: team_id.clone(),
                max_hp: max_hp.clone(),
                vision_range: vision_range.clone(),
                vision_fov: vision_fov.clone(),
                hearing_range: hearing_range.clone(),
            }),
            Reducer::StartLobby { lobby_id } => {
                __sats::bsatn::to_vec(&start_lobby_reducer::StartLobbyArgs {
                    lobby_id: lobby_id.clone(),
                })
            }
            Reducer::SubmitAction {
                entity_id,
                action_kind,
                direction_x,
                direction_y,
                angle,
                target_x,
                target_y,
                target_entity_id,
                ability_slot,
                ability_target_kind,
                message,
                volume,
                signal_type,
                signal_data,
                prefab,
            } => __sats::bsatn::to_vec(&submit_action_reducer::SubmitActionArgs {
                entity_id: entity_id.clone(),
                action_kind: action_kind.clone(),
                direction_x: direction_x.clone(),
                direction_y: direction_y.clone(),
                angle: angle.clone(),
                target_x: target_x.clone(),
                target_y: target_y.clone(),
                target_entity_id: target_entity_id.clone(),
                ability_slot: ability_slot.clone(),
                ability_target_kind: ability_target_kind.clone(),
                message: message.clone(),
                volume: volume.clone(),
                signal_type: signal_type.clone(),
                signal_data: signal_data.clone(),
                prefab: prefab.clone(),
            }),
            _ => unreachable!(),
        }
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    action_submission: __sdk::TableUpdate<ActionSubmissionRow>,
    agent_constraints: __sdk::TableUpdate<AgentConstraintsRow>,
    agent_telemetry_tick: __sdk::TableUpdate<AgentTelemetryTickRow>,
    agent_tick_rollup: __sdk::TableUpdate<AgentTickRollupRow>,
    agent_tool_call_event: __sdk::TableUpdate<AgentToolCallEventRow>,
    collider: __sdk::TableUpdate<ColliderRow>,
    color_rect: __sdk::TableUpdate<ColorRectRow>,
    combat_event: __sdk::TableUpdate<CombatEventRow>,
    connected_agent: __sdk::TableUpdate<ConnectedAgentRow>,
    entity: __sdk::TableUpdate<EntityRow>,
    game_match: __sdk::TableUpdate<GameMatchRow>,
    health: __sdk::TableUpdate<HealthRow>,
    label: __sdk::TableUpdate<LabelRow>,
    lobby: __sdk::TableUpdate<LobbyRow>,
    lobby_member: __sdk::TableUpdate<LobbyMemberRow>,
    match_participant: __sdk::TableUpdate<MatchParticipantRow>,
    match_queue: __sdk::TableUpdate<MatchQueueRow>,
    movement: __sdk::TableUpdate<MovementRow>,
    observation_event: __sdk::TableUpdate<ObservationEventRow>,
    perception: __sdk::TableUpdate<PerceptionRow>,
    remote_topology_document: __sdk::TableUpdate<RemoteTopologyDocumentRow>,
    rigid_body: __sdk::TableUpdate<RigidBodyRow>,
    script: __sdk::TableUpdate<ScriptRow>,
    speech_event: __sdk::TableUpdate<SpeechEventRow>,
    sprite: __sdk::TableUpdate<SpriteRow>,
    transform: __sdk::TableUpdate<TransformRow>,
    velocity: __sdk::TableUpdate<VelocityRow>,
    world_event: __sdk::TableUpdate<WorldEventRow>,
    world_state: __sdk::TableUpdate<WorldStateRow>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "action_submission" => db_update
                    .action_submission
                    .append(action_submission_table::parse_table_update(table_update)?),
                "agent_constraints" => db_update
                    .agent_constraints
                    .append(agent_constraints_table::parse_table_update(table_update)?),
                "agent_telemetry_tick" => db_update.agent_telemetry_tick.append(
                    agent_telemetry_tick_table::parse_table_update(table_update)?,
                ),
                "agent_tick_rollup" => db_update
                    .agent_tick_rollup
                    .append(agent_tick_rollup_table::parse_table_update(table_update)?),
                "agent_tool_call_event" => db_update.agent_tool_call_event.append(
                    agent_tool_call_event_table::parse_table_update(table_update)?,
                ),
                "collider" => db_update
                    .collider
                    .append(collider_table::parse_table_update(table_update)?),
                "color_rect" => db_update
                    .color_rect
                    .append(color_rect_table::parse_table_update(table_update)?),
                "combat_event" => db_update
                    .combat_event
                    .append(combat_event_table::parse_table_update(table_update)?),
                "connected_agent" => db_update
                    .connected_agent
                    .append(connected_agent_table::parse_table_update(table_update)?),
                "entity" => db_update
                    .entity
                    .append(entity_table::parse_table_update(table_update)?),
                "game_match" => db_update
                    .game_match
                    .append(game_match_table::parse_table_update(table_update)?),
                "health" => db_update
                    .health
                    .append(health_table::parse_table_update(table_update)?),
                "label" => db_update
                    .label
                    .append(label_table::parse_table_update(table_update)?),
                "lobby" => db_update
                    .lobby
                    .append(lobby_table::parse_table_update(table_update)?),
                "lobby_member" => db_update
                    .lobby_member
                    .append(lobby_member_table::parse_table_update(table_update)?),
                "match_participant" => db_update
                    .match_participant
                    .append(match_participant_table::parse_table_update(table_update)?),
                "match_queue" => db_update
                    .match_queue
                    .append(match_queue_table::parse_table_update(table_update)?),
                "movement" => db_update
                    .movement
                    .append(movement_table::parse_table_update(table_update)?),
                "observation_event" => db_update
                    .observation_event
                    .append(observation_event_table::parse_table_update(table_update)?),
                "perception" => db_update
                    .perception
                    .append(perception_table::parse_table_update(table_update)?),
                "remote_topology_document" => db_update.remote_topology_document.append(
                    remote_topology_document_table::parse_table_update(table_update)?,
                ),
                "rigid_body" => db_update
                    .rigid_body
                    .append(rigid_body_table::parse_table_update(table_update)?),
                "script" => db_update
                    .script
                    .append(script_table::parse_table_update(table_update)?),
                "speech_event" => db_update
                    .speech_event
                    .append(speech_event_table::parse_table_update(table_update)?),
                "sprite" => db_update
                    .sprite
                    .append(sprite_table::parse_table_update(table_update)?),
                "transform" => db_update
                    .transform
                    .append(transform_table::parse_table_update(table_update)?),
                "velocity" => db_update
                    .velocity
                    .append(velocity_table::parse_table_update(table_update)?),
                "world_event" => db_update
                    .world_event
                    .append(world_event_table::parse_table_update(table_update)?),
                "world_state" => db_update
                    .world_state
                    .append(world_state_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.action_submission = cache
            .apply_diff_to_table::<ActionSubmissionRow>(
                "action_submission",
                &self.action_submission,
            )
            .with_updates_by_pk(|row| &row.submission_id);
        diff.agent_constraints = cache
            .apply_diff_to_table::<AgentConstraintsRow>(
                "agent_constraints",
                &self.agent_constraints,
            )
            .with_updates_by_pk(|row| &row.entity_id);
        diff.agent_telemetry_tick = cache
            .apply_diff_to_table::<AgentTelemetryTickRow>(
                "agent_telemetry_tick",
                &self.agent_telemetry_tick,
            )
            .with_updates_by_pk(|row| &row.row_id);
        diff.agent_tick_rollup = cache
            .apply_diff_to_table::<AgentTickRollupRow>("agent_tick_rollup", &self.agent_tick_rollup)
            .with_updates_by_pk(|row| &row.row_id);
        diff.agent_tool_call_event = cache
            .apply_diff_to_table::<AgentToolCallEventRow>(
                "agent_tool_call_event",
                &self.agent_tool_call_event,
            )
            .with_updates_by_pk(|row| &row.row_id);
        diff.collider = cache
            .apply_diff_to_table::<ColliderRow>("collider", &self.collider)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.color_rect = cache
            .apply_diff_to_table::<ColorRectRow>("color_rect", &self.color_rect)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.combat_event = cache
            .apply_diff_to_table::<CombatEventRow>("combat_event", &self.combat_event)
            .with_updates_by_pk(|row| &row.event_id);
        diff.connected_agent = cache
            .apply_diff_to_table::<ConnectedAgentRow>("connected_agent", &self.connected_agent)
            .with_updates_by_pk(|row| &row.identity);
        diff.entity = cache
            .apply_diff_to_table::<EntityRow>("entity", &self.entity)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.game_match = cache
            .apply_diff_to_table::<GameMatchRow>("game_match", &self.game_match)
            .with_updates_by_pk(|row| &row.match_id);
        diff.health = cache
            .apply_diff_to_table::<HealthRow>("health", &self.health)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.label = cache
            .apply_diff_to_table::<LabelRow>("label", &self.label)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.lobby = cache
            .apply_diff_to_table::<LobbyRow>("lobby", &self.lobby)
            .with_updates_by_pk(|row| &row.lobby_id);
        diff.lobby_member = cache
            .apply_diff_to_table::<LobbyMemberRow>("lobby_member", &self.lobby_member)
            .with_updates_by_pk(|row| &row.membership_id);
        diff.match_participant = cache
            .apply_diff_to_table::<MatchParticipantRow>(
                "match_participant",
                &self.match_participant,
            )
            .with_updates_by_pk(|row| &row.participant_id);
        diff.match_queue = cache
            .apply_diff_to_table::<MatchQueueRow>("match_queue", &self.match_queue)
            .with_updates_by_pk(|row| &row.queue_id);
        diff.movement = cache
            .apply_diff_to_table::<MovementRow>("movement", &self.movement)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.observation_event = cache
            .apply_diff_to_table::<ObservationEventRow>(
                "observation_event",
                &self.observation_event,
            )
            .with_updates_by_pk(|row| &row.event_id);
        diff.perception = cache
            .apply_diff_to_table::<PerceptionRow>("perception", &self.perception)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.remote_topology_document = cache
            .apply_diff_to_table::<RemoteTopologyDocumentRow>(
                "remote_topology_document",
                &self.remote_topology_document,
            )
            .with_updates_by_pk(|row| &row.row_id);
        diff.rigid_body = cache
            .apply_diff_to_table::<RigidBodyRow>("rigid_body", &self.rigid_body)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.script = cache
            .apply_diff_to_table::<ScriptRow>("script", &self.script)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.speech_event = cache
            .apply_diff_to_table::<SpeechEventRow>("speech_event", &self.speech_event)
            .with_updates_by_pk(|row| &row.event_id);
        diff.sprite = cache
            .apply_diff_to_table::<SpriteRow>("sprite", &self.sprite)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.transform = cache
            .apply_diff_to_table::<TransformRow>("transform", &self.transform)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.velocity = cache
            .apply_diff_to_table::<VelocityRow>("velocity", &self.velocity)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.world_event = cache
            .apply_diff_to_table::<WorldEventRow>("world_event", &self.world_event)
            .with_updates_by_pk(|row| &row.event_id);
        diff.world_state = cache
            .apply_diff_to_table::<WorldStateRow>("world_state", &self.world_state)
            .with_updates_by_pk(|row| &row.id);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "action_submission" => db_update
                    .action_submission
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "agent_constraints" => db_update
                    .agent_constraints
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "agent_telemetry_tick" => db_update
                    .agent_telemetry_tick
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "agent_tick_rollup" => db_update
                    .agent_tick_rollup
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "agent_tool_call_event" => db_update
                    .agent_tool_call_event
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "collider" => db_update
                    .collider
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "color_rect" => db_update
                    .color_rect
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "combat_event" => db_update
                    .combat_event
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "connected_agent" => db_update
                    .connected_agent
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "entity" => db_update
                    .entity
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "game_match" => db_update
                    .game_match
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "health" => db_update
                    .health
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "label" => db_update
                    .label
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "lobby" => db_update
                    .lobby
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "lobby_member" => db_update
                    .lobby_member
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "match_participant" => db_update
                    .match_participant
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "match_queue" => db_update
                    .match_queue
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "movement" => db_update
                    .movement
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "observation_event" => db_update
                    .observation_event
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "perception" => db_update
                    .perception
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "remote_topology_document" => db_update
                    .remote_topology_document
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "rigid_body" => db_update
                    .rigid_body
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "script" => db_update
                    .script
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "speech_event" => db_update
                    .speech_event
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "sprite" => db_update
                    .sprite
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "transform" => db_update
                    .transform
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "velocity" => db_update
                    .velocity
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "world_event" => db_update
                    .world_event
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "world_state" => db_update
                    .world_state
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "action_submission" => db_update
                    .action_submission
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "agent_constraints" => db_update
                    .agent_constraints
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "agent_telemetry_tick" => db_update
                    .agent_telemetry_tick
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "agent_tick_rollup" => db_update
                    .agent_tick_rollup
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "agent_tool_call_event" => db_update
                    .agent_tool_call_event
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "collider" => db_update
                    .collider
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "color_rect" => db_update
                    .color_rect
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "combat_event" => db_update
                    .combat_event
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "connected_agent" => db_update
                    .connected_agent
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "entity" => db_update
                    .entity
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "game_match" => db_update
                    .game_match
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "health" => db_update
                    .health
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "label" => db_update
                    .label
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "lobby" => db_update
                    .lobby
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "lobby_member" => db_update
                    .lobby_member
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "match_participant" => db_update
                    .match_participant
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "match_queue" => db_update
                    .match_queue
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "movement" => db_update
                    .movement
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "observation_event" => db_update
                    .observation_event
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "perception" => db_update
                    .perception
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "remote_topology_document" => db_update
                    .remote_topology_document
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "rigid_body" => db_update
                    .rigid_body
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "script" => db_update
                    .script
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "speech_event" => db_update
                    .speech_event
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "sprite" => db_update
                    .sprite
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "transform" => db_update
                    .transform
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "velocity" => db_update
                    .velocity
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "world_event" => db_update
                    .world_event
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "world_state" => db_update
                    .world_state
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    action_submission: __sdk::TableAppliedDiff<'r, ActionSubmissionRow>,
    agent_constraints: __sdk::TableAppliedDiff<'r, AgentConstraintsRow>,
    agent_telemetry_tick: __sdk::TableAppliedDiff<'r, AgentTelemetryTickRow>,
    agent_tick_rollup: __sdk::TableAppliedDiff<'r, AgentTickRollupRow>,
    agent_tool_call_event: __sdk::TableAppliedDiff<'r, AgentToolCallEventRow>,
    collider: __sdk::TableAppliedDiff<'r, ColliderRow>,
    color_rect: __sdk::TableAppliedDiff<'r, ColorRectRow>,
    combat_event: __sdk::TableAppliedDiff<'r, CombatEventRow>,
    connected_agent: __sdk::TableAppliedDiff<'r, ConnectedAgentRow>,
    entity: __sdk::TableAppliedDiff<'r, EntityRow>,
    game_match: __sdk::TableAppliedDiff<'r, GameMatchRow>,
    health: __sdk::TableAppliedDiff<'r, HealthRow>,
    label: __sdk::TableAppliedDiff<'r, LabelRow>,
    lobby: __sdk::TableAppliedDiff<'r, LobbyRow>,
    lobby_member: __sdk::TableAppliedDiff<'r, LobbyMemberRow>,
    match_participant: __sdk::TableAppliedDiff<'r, MatchParticipantRow>,
    match_queue: __sdk::TableAppliedDiff<'r, MatchQueueRow>,
    movement: __sdk::TableAppliedDiff<'r, MovementRow>,
    observation_event: __sdk::TableAppliedDiff<'r, ObservationEventRow>,
    perception: __sdk::TableAppliedDiff<'r, PerceptionRow>,
    remote_topology_document: __sdk::TableAppliedDiff<'r, RemoteTopologyDocumentRow>,
    rigid_body: __sdk::TableAppliedDiff<'r, RigidBodyRow>,
    script: __sdk::TableAppliedDiff<'r, ScriptRow>,
    speech_event: __sdk::TableAppliedDiff<'r, SpeechEventRow>,
    sprite: __sdk::TableAppliedDiff<'r, SpriteRow>,
    transform: __sdk::TableAppliedDiff<'r, TransformRow>,
    velocity: __sdk::TableAppliedDiff<'r, VelocityRow>,
    world_event: __sdk::TableAppliedDiff<'r, WorldEventRow>,
    world_state: __sdk::TableAppliedDiff<'r, WorldStateRow>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<ActionSubmissionRow>(
            "action_submission",
            &self.action_submission,
            event,
        );
        callbacks.invoke_table_row_callbacks::<AgentConstraintsRow>(
            "agent_constraints",
            &self.agent_constraints,
            event,
        );
        callbacks.invoke_table_row_callbacks::<AgentTelemetryTickRow>(
            "agent_telemetry_tick",
            &self.agent_telemetry_tick,
            event,
        );
        callbacks.invoke_table_row_callbacks::<AgentTickRollupRow>(
            "agent_tick_rollup",
            &self.agent_tick_rollup,
            event,
        );
        callbacks.invoke_table_row_callbacks::<AgentToolCallEventRow>(
            "agent_tool_call_event",
            &self.agent_tool_call_event,
            event,
        );
        callbacks.invoke_table_row_callbacks::<ColliderRow>("collider", &self.collider, event);
        callbacks.invoke_table_row_callbacks::<ColorRectRow>("color_rect", &self.color_rect, event);
        callbacks.invoke_table_row_callbacks::<CombatEventRow>(
            "combat_event",
            &self.combat_event,
            event,
        );
        callbacks.invoke_table_row_callbacks::<ConnectedAgentRow>(
            "connected_agent",
            &self.connected_agent,
            event,
        );
        callbacks.invoke_table_row_callbacks::<EntityRow>("entity", &self.entity, event);
        callbacks.invoke_table_row_callbacks::<GameMatchRow>("game_match", &self.game_match, event);
        callbacks.invoke_table_row_callbacks::<HealthRow>("health", &self.health, event);
        callbacks.invoke_table_row_callbacks::<LabelRow>("label", &self.label, event);
        callbacks.invoke_table_row_callbacks::<LobbyRow>("lobby", &self.lobby, event);
        callbacks.invoke_table_row_callbacks::<LobbyMemberRow>(
            "lobby_member",
            &self.lobby_member,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MatchParticipantRow>(
            "match_participant",
            &self.match_participant,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MatchQueueRow>(
            "match_queue",
            &self.match_queue,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MovementRow>("movement", &self.movement, event);
        callbacks.invoke_table_row_callbacks::<ObservationEventRow>(
            "observation_event",
            &self.observation_event,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PerceptionRow>(
            "perception",
            &self.perception,
            event,
        );
        callbacks.invoke_table_row_callbacks::<RemoteTopologyDocumentRow>(
            "remote_topology_document",
            &self.remote_topology_document,
            event,
        );
        callbacks.invoke_table_row_callbacks::<RigidBodyRow>("rigid_body", &self.rigid_body, event);
        callbacks.invoke_table_row_callbacks::<ScriptRow>("script", &self.script, event);
        callbacks.invoke_table_row_callbacks::<SpeechEventRow>(
            "speech_event",
            &self.speech_event,
            event,
        );
        callbacks.invoke_table_row_callbacks::<SpriteRow>("sprite", &self.sprite, event);
        callbacks.invoke_table_row_callbacks::<TransformRow>("transform", &self.transform, event);
        callbacks.invoke_table_row_callbacks::<VelocityRow>("velocity", &self.velocity, event);
        callbacks.invoke_table_row_callbacks::<WorldEventRow>(
            "world_event",
            &self.world_event,
            event,
        );
        callbacks.invoke_table_row_callbacks::<WorldStateRow>(
            "world_state",
            &self.world_state,
            event,
        );
    }
}

#[doc(hidden)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
/// - [`DbConnection::run_threaded`].
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
/// - [`DbConnection::advance_one_message_blocking`].
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        action_submission_table::register_table(client_cache);
        agent_constraints_table::register_table(client_cache);
        agent_telemetry_tick_table::register_table(client_cache);
        agent_tick_rollup_table::register_table(client_cache);
        agent_tool_call_event_table::register_table(client_cache);
        collider_table::register_table(client_cache);
        color_rect_table::register_table(client_cache);
        combat_event_table::register_table(client_cache);
        connected_agent_table::register_table(client_cache);
        entity_table::register_table(client_cache);
        game_match_table::register_table(client_cache);
        health_table::register_table(client_cache);
        label_table::register_table(client_cache);
        lobby_table::register_table(client_cache);
        lobby_member_table::register_table(client_cache);
        match_participant_table::register_table(client_cache);
        match_queue_table::register_table(client_cache);
        movement_table::register_table(client_cache);
        observation_event_table::register_table(client_cache);
        perception_table::register_table(client_cache);
        remote_topology_document_table::register_table(client_cache);
        rigid_body_table::register_table(client_cache);
        script_table::register_table(client_cache);
        speech_event_table::register_table(client_cache);
        sprite_table::register_table(client_cache);
        transform_table::register_table(client_cache);
        velocity_table::register_table(client_cache);
        world_event_table::register_table(client_cache);
        world_state_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "action_submission",
        "agent_constraints",
        "agent_telemetry_tick",
        "agent_tick_rollup",
        "agent_tool_call_event",
        "collider",
        "color_rect",
        "combat_event",
        "connected_agent",
        "entity",
        "game_match",
        "health",
        "label",
        "lobby",
        "lobby_member",
        "match_participant",
        "match_queue",
        "movement",
        "observation_event",
        "perception",
        "remote_topology_document",
        "rigid_body",
        "script",
        "speech_event",
        "sprite",
        "transform",
        "velocity",
        "world_event",
        "world_state",
    ];
}
