// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MovementRow {
    pub entity_id: u64,
    pub max_speed: f32,
    pub acceleration: f32,
    pub deceleration: f32,
    pub turn_rate: f32,
}

impl __sdk::InModule for MovementRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MovementRow`.
///
/// Provides typed access to columns for query building.
pub struct MovementRowCols {
    pub entity_id: __sdk::__query_builder::Col<MovementRow, u64>,
    pub max_speed: __sdk::__query_builder::Col<MovementRow, f32>,
    pub acceleration: __sdk::__query_builder::Col<MovementRow, f32>,
    pub deceleration: __sdk::__query_builder::Col<MovementRow, f32>,
    pub turn_rate: __sdk::__query_builder::Col<MovementRow, f32>,
}

impl __sdk::__query_builder::HasCols for MovementRow {
    type Cols = MovementRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MovementRowCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            max_speed: __sdk::__query_builder::Col::new(table_name, "max_speed"),
            acceleration: __sdk::__query_builder::Col::new(table_name, "acceleration"),
            deceleration: __sdk::__query_builder::Col::new(table_name, "deceleration"),
            turn_rate: __sdk::__query_builder::Col::new(table_name, "turn_rate"),
        }
    }
}

/// Indexed column accessor struct for the table `MovementRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct MovementRowIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<MovementRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for MovementRow {
    type IxCols = MovementRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MovementRowIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MovementRow {}
