// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::observation_event_row_type::ObservationEventRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `observation_event`.
///
/// Obtain a handle from the [`ObservationEventTableAccess::observation_event`] method on [`super::RemoteTables`],
/// like `ctx.db.observation_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.observation_event().on_insert(...)`.
pub struct ObservationEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<ObservationEventRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `observation_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ObservationEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ObservationEventTableHandle`], which mediates access to the table `observation_event`.
    fn observation_event(&self) -> ObservationEventTableHandle<'_>;
}

impl ObservationEventTableAccess for super::RemoteTables {
    fn observation_event(&self) -> ObservationEventTableHandle<'_> {
        ObservationEventTableHandle {
            imp: self
                .imp
                .get_table::<ObservationEventRow>("observation_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ObservationEventInsertCallbackId(__sdk::CallbackId);
pub struct ObservationEventDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ObservationEventTableHandle<'ctx> {
    type Row = ObservationEventRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ObservationEventRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ObservationEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ObservationEventInsertCallbackId {
        ObservationEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ObservationEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ObservationEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ObservationEventDeleteCallbackId {
        ObservationEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ObservationEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ObservationEventUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ObservationEventTableHandle<'ctx> {
    type UpdateCallbackId = ObservationEventUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ObservationEventUpdateCallbackId {
        ObservationEventUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ObservationEventUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `event_id` unique index on the table `observation_event`,
/// which allows point queries on the field of the same name
/// via the [`ObservationEventEventIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.observation_event().event_id().find(...)`.
pub struct ObservationEventEventIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ObservationEventRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ObservationEventTableHandle<'ctx> {
    /// Get a handle on the `event_id` unique index on the table `observation_event`.
    pub fn event_id(&self) -> ObservationEventEventIdUnique<'ctx> {
        ObservationEventEventIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("event_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ObservationEventEventIdUnique<'ctx> {
    /// Find the subscribed row whose `event_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ObservationEventRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ObservationEventRow>("observation_event");
    _table.add_unique_constraint::<u64>("event_id", |row| &row.event_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ObservationEventRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ObservationEventRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ObservationEventRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait observation_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ObservationEventRow`.
    fn observation_event(&self) -> __sdk::__query_builder::Table<ObservationEventRow>;
}

impl observation_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn observation_event(&self) -> __sdk::__query_builder::Table<ObservationEventRow> {
        __sdk::__query_builder::Table::new("observation_event")
    }
}
