// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ObservationEventRow {
    pub event_id: u64,
    pub tick: u64,
    pub observer_entity_id: u64,
    pub owner_identity: Option<__sdk::Identity>,
    pub observation_json: String,
}

impl __sdk::InModule for ObservationEventRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ObservationEventRow`.
///
/// Provides typed access to columns for query building.
pub struct ObservationEventRowCols {
    pub event_id: __sdk::__query_builder::Col<ObservationEventRow, u64>,
    pub tick: __sdk::__query_builder::Col<ObservationEventRow, u64>,
    pub observer_entity_id: __sdk::__query_builder::Col<ObservationEventRow, u64>,
    pub owner_identity: __sdk::__query_builder::Col<ObservationEventRow, Option<__sdk::Identity>>,
    pub observation_json: __sdk::__query_builder::Col<ObservationEventRow, String>,
}

impl __sdk::__query_builder::HasCols for ObservationEventRow {
    type Cols = ObservationEventRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ObservationEventRowCols {
            event_id: __sdk::__query_builder::Col::new(table_name, "event_id"),
            tick: __sdk::__query_builder::Col::new(table_name, "tick"),
            observer_entity_id: __sdk::__query_builder::Col::new(table_name, "observer_entity_id"),
            owner_identity: __sdk::__query_builder::Col::new(table_name, "owner_identity"),
            observation_json: __sdk::__query_builder::Col::new(table_name, "observation_json"),
        }
    }
}

/// Indexed column accessor struct for the table `ObservationEventRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct ObservationEventRowIxCols {
    pub event_id: __sdk::__query_builder::IxCol<ObservationEventRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for ObservationEventRow {
    type IxCols = ObservationEventRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ObservationEventRowIxCols {
            event_id: __sdk::__query_builder::IxCol::new(table_name, "event_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ObservationEventRow {}
