// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PerceptionRow {
    pub entity_id: u64,
    pub vision_range: f32,
    pub vision_fov: f32,
    pub hearing_range: f32,
}

impl __sdk::InModule for PerceptionRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PerceptionRow`.
///
/// Provides typed access to columns for query building.
pub struct PerceptionRowCols {
    pub entity_id: __sdk::__query_builder::Col<PerceptionRow, u64>,
    pub vision_range: __sdk::__query_builder::Col<PerceptionRow, f32>,
    pub vision_fov: __sdk::__query_builder::Col<PerceptionRow, f32>,
    pub hearing_range: __sdk::__query_builder::Col<PerceptionRow, f32>,
}

impl __sdk::__query_builder::HasCols for PerceptionRow {
    type Cols = PerceptionRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PerceptionRowCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            vision_range: __sdk::__query_builder::Col::new(table_name, "vision_range"),
            vision_fov: __sdk::__query_builder::Col::new(table_name, "vision_fov"),
            hearing_range: __sdk::__query_builder::Col::new(table_name, "hearing_range"),
        }
    }
}

/// Indexed column accessor struct for the table `PerceptionRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct PerceptionRowIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<PerceptionRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for PerceptionRow {
    type IxCols = PerceptionRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PerceptionRowIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PerceptionRow {}
