// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::perception_row_type::PerceptionRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `perception`.
///
/// Obtain a handle from the [`PerceptionTableAccess::perception`] method on [`super::RemoteTables`],
/// like `ctx.db.perception()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.perception().on_insert(...)`.
pub struct PerceptionTableHandle<'ctx> {
    imp: __sdk::TableHandle<PerceptionRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `perception`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PerceptionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PerceptionTableHandle`], which mediates access to the table `perception`.
    fn perception(&self) -> PerceptionTableHandle<'_>;
}

impl PerceptionTableAccess for super::RemoteTables {
    fn perception(&self) -> PerceptionTableHandle<'_> {
        PerceptionTableHandle {
            imp: self.imp.get_table::<PerceptionRow>("perception"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PerceptionInsertCallbackId(__sdk::CallbackId);
pub struct PerceptionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PerceptionTableHandle<'ctx> {
    type Row = PerceptionRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PerceptionRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PerceptionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PerceptionInsertCallbackId {
        PerceptionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PerceptionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PerceptionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PerceptionDeleteCallbackId {
        PerceptionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PerceptionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PerceptionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PerceptionTableHandle<'ctx> {
    type UpdateCallbackId = PerceptionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PerceptionUpdateCallbackId {
        PerceptionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PerceptionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `perception`,
/// which allows point queries on the field of the same name
/// via the [`PerceptionEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.perception().entity_id().find(...)`.
pub struct PerceptionEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PerceptionRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PerceptionTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `perception`.
    pub fn entity_id(&self) -> PerceptionEntityIdUnique<'ctx> {
        PerceptionEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PerceptionEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PerceptionRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PerceptionRow>("perception");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PerceptionRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PerceptionRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PerceptionRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait perceptionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PerceptionRow`.
    fn perception(&self) -> __sdk::__query_builder::Table<PerceptionRow>;
}

impl perceptionQueryTableAccess for __sdk::QueryTableAccessor {
    fn perception(&self) -> __sdk::__query_builder::Table<PerceptionRow> {
        __sdk::__query_builder::Table::new("perception")
    }
}
