// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PublishRemoteTopologyDocumentArgs {
    pub topology_json: String,
}

impl From<PublishRemoteTopologyDocumentArgs> for super::Reducer {
    fn from(args: PublishRemoteTopologyDocumentArgs) -> Self {
        Self::PublishRemoteTopologyDocument {
            topology_json: args.topology_json,
        }
    }
}

impl __sdk::InModule for PublishRemoteTopologyDocumentArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `publish_remote_topology_document`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait publish_remote_topology_document {
    /// Request that the remote module invoke the reducer `publish_remote_topology_document` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`publish_remote_topology_document:publish_remote_topology_document_then`] to run a callback after the reducer completes.
    fn publish_remote_topology_document(&self, topology_json: String) -> __sdk::Result<()> {
        self.publish_remote_topology_document_then(topology_json, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `publish_remote_topology_document` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn publish_remote_topology_document_then(
        &self,
        topology_json: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl publish_remote_topology_document for super::RemoteReducers {
    fn publish_remote_topology_document_then(
        &self,
        topology_json: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PublishRemoteTopologyDocumentArgs { topology_json },
            callback,
        )
    }
}
