// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::remote_topology_document_row_type::RemoteTopologyDocumentRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `remote_topology_document`.
///
/// Obtain a handle from the [`RemoteTopologyDocumentTableAccess::remote_topology_document`] method on [`super::RemoteTables`],
/// like `ctx.db.remote_topology_document()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.remote_topology_document().on_insert(...)`.
pub struct RemoteTopologyDocumentTableHandle<'ctx> {
    imp: __sdk::TableHandle<RemoteTopologyDocumentRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `remote_topology_document`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RemoteTopologyDocumentTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RemoteTopologyDocumentTableHandle`], which mediates access to the table `remote_topology_document`.
    fn remote_topology_document(&self) -> RemoteTopologyDocumentTableHandle<'_>;
}

impl RemoteTopologyDocumentTableAccess for super::RemoteTables {
    fn remote_topology_document(&self) -> RemoteTopologyDocumentTableHandle<'_> {
        RemoteTopologyDocumentTableHandle {
            imp: self
                .imp
                .get_table::<RemoteTopologyDocumentRow>("remote_topology_document"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RemoteTopologyDocumentInsertCallbackId(__sdk::CallbackId);
pub struct RemoteTopologyDocumentDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RemoteTopologyDocumentTableHandle<'ctx> {
    type Row = RemoteTopologyDocumentRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RemoteTopologyDocumentRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RemoteTopologyDocumentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RemoteTopologyDocumentInsertCallbackId {
        RemoteTopologyDocumentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RemoteTopologyDocumentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RemoteTopologyDocumentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RemoteTopologyDocumentDeleteCallbackId {
        RemoteTopologyDocumentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RemoteTopologyDocumentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RemoteTopologyDocumentUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RemoteTopologyDocumentTableHandle<'ctx> {
    type UpdateCallbackId = RemoteTopologyDocumentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RemoteTopologyDocumentUpdateCallbackId {
        RemoteTopologyDocumentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RemoteTopologyDocumentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `row_id` unique index on the table `remote_topology_document`,
/// which allows point queries on the field of the same name
/// via the [`RemoteTopologyDocumentRowIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.remote_topology_document().row_id().find(...)`.
pub struct RemoteTopologyDocumentRowIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RemoteTopologyDocumentRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RemoteTopologyDocumentTableHandle<'ctx> {
    /// Get a handle on the `row_id` unique index on the table `remote_topology_document`.
    pub fn row_id(&self) -> RemoteTopologyDocumentRowIdUnique<'ctx> {
        RemoteTopologyDocumentRowIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("row_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RemoteTopologyDocumentRowIdUnique<'ctx> {
    /// Find the subscribed row whose `row_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<RemoteTopologyDocumentRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<RemoteTopologyDocumentRow>("remote_topology_document");
    _table.add_unique_constraint::<u64>("row_id", |row| &row.row_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RemoteTopologyDocumentRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RemoteTopologyDocumentRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RemoteTopologyDocumentRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait remote_topology_documentQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RemoteTopologyDocumentRow`.
    fn remote_topology_document(&self) -> __sdk::__query_builder::Table<RemoteTopologyDocumentRow>;
}

impl remote_topology_documentQueryTableAccess for __sdk::QueryTableAccessor {
    fn remote_topology_document(&self) -> __sdk::__query_builder::Table<RemoteTopologyDocumentRow> {
        __sdk::__query_builder::Table::new("remote_topology_document")
    }
}
