// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RemoteTopologyDocumentRow {
    pub row_id: u64,
    pub generated_at_unix_ms: u64,
    pub scenario_id: String,
    pub profile_id: String,
    pub world_count: u32,
    pub team_count: u32,
    pub topology_json: String,
}

impl __sdk::InModule for RemoteTopologyDocumentRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RemoteTopologyDocumentRow`.
///
/// Provides typed access to columns for query building.
pub struct RemoteTopologyDocumentRowCols {
    pub row_id: __sdk::__query_builder::Col<RemoteTopologyDocumentRow, u64>,
    pub generated_at_unix_ms: __sdk::__query_builder::Col<RemoteTopologyDocumentRow, u64>,
    pub scenario_id: __sdk::__query_builder::Col<RemoteTopologyDocumentRow, String>,
    pub profile_id: __sdk::__query_builder::Col<RemoteTopologyDocumentRow, String>,
    pub world_count: __sdk::__query_builder::Col<RemoteTopologyDocumentRow, u32>,
    pub team_count: __sdk::__query_builder::Col<RemoteTopologyDocumentRow, u32>,
    pub topology_json: __sdk::__query_builder::Col<RemoteTopologyDocumentRow, String>,
}

impl __sdk::__query_builder::HasCols for RemoteTopologyDocumentRow {
    type Cols = RemoteTopologyDocumentRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RemoteTopologyDocumentRowCols {
            row_id: __sdk::__query_builder::Col::new(table_name, "row_id"),
            generated_at_unix_ms: __sdk::__query_builder::Col::new(
                table_name,
                "generated_at_unix_ms",
            ),
            scenario_id: __sdk::__query_builder::Col::new(table_name, "scenario_id"),
            profile_id: __sdk::__query_builder::Col::new(table_name, "profile_id"),
            world_count: __sdk::__query_builder::Col::new(table_name, "world_count"),
            team_count: __sdk::__query_builder::Col::new(table_name, "team_count"),
            topology_json: __sdk::__query_builder::Col::new(table_name, "topology_json"),
        }
    }
}

/// Indexed column accessor struct for the table `RemoteTopologyDocumentRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct RemoteTopologyDocumentRowIxCols {
    pub row_id: __sdk::__query_builder::IxCol<RemoteTopologyDocumentRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for RemoteTopologyDocumentRow {
    type IxCols = RemoteTopologyDocumentRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RemoteTopologyDocumentRowIxCols {
            row_id: __sdk::__query_builder::IxCol::new(table_name, "row_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RemoteTopologyDocumentRow {}
