// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::body_kind_type::BodyKind;
use super::rigid_body_row_type::RigidBodyRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `rigid_body`.
///
/// Obtain a handle from the [`RigidBodyTableAccess::rigid_body`] method on [`super::RemoteTables`],
/// like `ctx.db.rigid_body()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.rigid_body().on_insert(...)`.
pub struct RigidBodyTableHandle<'ctx> {
    imp: __sdk::TableHandle<RigidBodyRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `rigid_body`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RigidBodyTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RigidBodyTableHandle`], which mediates access to the table `rigid_body`.
    fn rigid_body(&self) -> RigidBodyTableHandle<'_>;
}

impl RigidBodyTableAccess for super::RemoteTables {
    fn rigid_body(&self) -> RigidBodyTableHandle<'_> {
        RigidBodyTableHandle {
            imp: self.imp.get_table::<RigidBodyRow>("rigid_body"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RigidBodyInsertCallbackId(__sdk::CallbackId);
pub struct RigidBodyDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RigidBodyTableHandle<'ctx> {
    type Row = RigidBodyRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RigidBodyRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RigidBodyInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RigidBodyInsertCallbackId {
        RigidBodyInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RigidBodyInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RigidBodyDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RigidBodyDeleteCallbackId {
        RigidBodyDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RigidBodyDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RigidBodyUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RigidBodyTableHandle<'ctx> {
    type UpdateCallbackId = RigidBodyUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RigidBodyUpdateCallbackId {
        RigidBodyUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RigidBodyUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `rigid_body`,
/// which allows point queries on the field of the same name
/// via the [`RigidBodyEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.rigid_body().entity_id().find(...)`.
pub struct RigidBodyEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RigidBodyRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RigidBodyTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `rigid_body`.
    pub fn entity_id(&self) -> RigidBodyEntityIdUnique<'ctx> {
        RigidBodyEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RigidBodyEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<RigidBodyRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RigidBodyRow>("rigid_body");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RigidBodyRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RigidBodyRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RigidBodyRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait rigid_bodyQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RigidBodyRow`.
    fn rigid_body(&self) -> __sdk::__query_builder::Table<RigidBodyRow>;
}

impl rigid_bodyQueryTableAccess for __sdk::QueryTableAccessor {
    fn rigid_body(&self) -> __sdk::__query_builder::Table<RigidBodyRow> {
        __sdk::__query_builder::Table::new("rigid_body")
    }
}
