// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::body_kind_type::BodyKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RigidBodyRow {
    pub entity_id: u64,
    pub body_kind: BodyKind,
    pub mass: f32,
    pub friction: f32,
    pub restitution: f32,
    pub gravity_scale: f32,
}

impl __sdk::InModule for RigidBodyRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RigidBodyRow`.
///
/// Provides typed access to columns for query building.
pub struct RigidBodyRowCols {
    pub entity_id: __sdk::__query_builder::Col<RigidBodyRow, u64>,
    pub body_kind: __sdk::__query_builder::Col<RigidBodyRow, BodyKind>,
    pub mass: __sdk::__query_builder::Col<RigidBodyRow, f32>,
    pub friction: __sdk::__query_builder::Col<RigidBodyRow, f32>,
    pub restitution: __sdk::__query_builder::Col<RigidBodyRow, f32>,
    pub gravity_scale: __sdk::__query_builder::Col<RigidBodyRow, f32>,
}

impl __sdk::__query_builder::HasCols for RigidBodyRow {
    type Cols = RigidBodyRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RigidBodyRowCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            body_kind: __sdk::__query_builder::Col::new(table_name, "body_kind"),
            mass: __sdk::__query_builder::Col::new(table_name, "mass"),
            friction: __sdk::__query_builder::Col::new(table_name, "friction"),
            restitution: __sdk::__query_builder::Col::new(table_name, "restitution"),
            gravity_scale: __sdk::__query_builder::Col::new(table_name, "gravity_scale"),
        }
    }
}

/// Indexed column accessor struct for the table `RigidBodyRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct RigidBodyRowIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<RigidBodyRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for RigidBodyRow {
    type IxCols = RigidBodyRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RigidBodyRowIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RigidBodyRow {}
