// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::script_row_type::ScriptRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `script`.
///
/// Obtain a handle from the [`ScriptTableAccess::script`] method on [`super::RemoteTables`],
/// like `ctx.db.script()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.script().on_insert(...)`.
pub struct ScriptTableHandle<'ctx> {
    imp: __sdk::TableHandle<ScriptRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `script`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ScriptTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ScriptTableHandle`], which mediates access to the table `script`.
    fn script(&self) -> ScriptTableHandle<'_>;
}

impl ScriptTableAccess for super::RemoteTables {
    fn script(&self) -> ScriptTableHandle<'_> {
        ScriptTableHandle {
            imp: self.imp.get_table::<ScriptRow>("script"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ScriptInsertCallbackId(__sdk::CallbackId);
pub struct ScriptDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ScriptTableHandle<'ctx> {
    type Row = ScriptRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ScriptRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ScriptInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ScriptInsertCallbackId {
        ScriptInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ScriptInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ScriptDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ScriptDeleteCallbackId {
        ScriptDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ScriptDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ScriptUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ScriptTableHandle<'ctx> {
    type UpdateCallbackId = ScriptUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ScriptUpdateCallbackId {
        ScriptUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ScriptUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `script`,
/// which allows point queries on the field of the same name
/// via the [`ScriptEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.script().entity_id().find(...)`.
pub struct ScriptEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ScriptRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ScriptTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `script`.
    pub fn entity_id(&self) -> ScriptEntityIdUnique<'ctx> {
        ScriptEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ScriptEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ScriptRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ScriptRow>("script");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ScriptRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ScriptRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ScriptRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait scriptQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ScriptRow`.
    fn script(&self) -> __sdk::__query_builder::Table<ScriptRow>;
}

impl scriptQueryTableAccess for __sdk::QueryTableAccessor {
    fn script(&self) -> __sdk::__query_builder::Table<ScriptRow> {
        __sdk::__query_builder::Table::new("script")
    }
}
