// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ScriptRow {
    pub entity_id: u64,
    pub source: String,
    pub enabled: bool,
}

impl __sdk::InModule for ScriptRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ScriptRow`.
///
/// Provides typed access to columns for query building.
pub struct ScriptRowCols {
    pub entity_id: __sdk::__query_builder::Col<ScriptRow, u64>,
    pub source: __sdk::__query_builder::Col<ScriptRow, String>,
    pub enabled: __sdk::__query_builder::Col<ScriptRow, bool>,
}

impl __sdk::__query_builder::HasCols for ScriptRow {
    type Cols = ScriptRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ScriptRowCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            enabled: __sdk::__query_builder::Col::new(table_name, "enabled"),
        }
    }
}

/// Indexed column accessor struct for the table `ScriptRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct ScriptRowIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<ScriptRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for ScriptRow {
    type IxCols = ScriptRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ScriptRowIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ScriptRow {}
