// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetLobbyReadyArgs {
    pub lobby_id: u64,
    pub is_ready: bool,
}

impl From<SetLobbyReadyArgs> for super::Reducer {
    fn from(args: SetLobbyReadyArgs) -> Self {
        Self::SetLobbyReady {
            lobby_id: args.lobby_id,
            is_ready: args.is_ready,
        }
    }
}

impl __sdk::InModule for SetLobbyReadyArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_lobby_ready`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_lobby_ready {
    /// Request that the remote module invoke the reducer `set_lobby_ready` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_lobby_ready:set_lobby_ready_then`] to run a callback after the reducer completes.
    fn set_lobby_ready(&self, lobby_id: u64, is_ready: bool) -> __sdk::Result<()> {
        self.set_lobby_ready_then(lobby_id, is_ready, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_lobby_ready` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_lobby_ready_then(
        &self,
        lobby_id: u64,
        is_ready: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_lobby_ready for super::RemoteReducers {
    fn set_lobby_ready_then(
        &self,
        lobby_id: u64,
        is_ready: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetLobbyReadyArgs { lobby_id, is_ready }, callback)
    }
}
