// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::agent_type_type::AgentType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SpawnEntityArgs {
    pub pos_x: f32,
    pub pos_y: f32,
    pub agent_type: Option<AgentType>,
}

impl From<SpawnEntityArgs> for super::Reducer {
    fn from(args: SpawnEntityArgs) -> Self {
        Self::SpawnEntity {
            pos_x: args.pos_x,
            pos_y: args.pos_y,
            agent_type: args.agent_type,
        }
    }
}

impl __sdk::InModule for SpawnEntityArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `spawn_entity`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait spawn_entity {
    /// Request that the remote module invoke the reducer `spawn_entity` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`spawn_entity:spawn_entity_then`] to run a callback after the reducer completes.
    fn spawn_entity(
        &self,
        pos_x: f32,
        pos_y: f32,
        agent_type: Option<AgentType>,
    ) -> __sdk::Result<()> {
        self.spawn_entity_then(pos_x, pos_y, agent_type, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `spawn_entity` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn spawn_entity_then(
        &self,
        pos_x: f32,
        pos_y: f32,
        agent_type: Option<AgentType>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl spawn_entity for super::RemoteReducers {
    fn spawn_entity_then(
        &self,
        pos_x: f32,
        pos_y: f32,
        agent_type: Option<AgentType>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SpawnEntityArgs {
                pos_x,
                pos_y,
                agent_type,
            },
            callback,
        )
    }
}
