// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::agent_type_type::AgentType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SpawnEntityFullArgs {
    pub pos_x: f32,
    pub pos_y: f32,
    pub agent_type: Option<AgentType>,
    pub rect_width: f32,
    pub rect_height: f32,
    pub color_r: f32,
    pub color_g: f32,
    pub color_b: f32,
    pub color_a: f32,
    pub label_name: String,
    pub team_id: u8,
    pub max_hp: f32,
    pub vision_range: f32,
    pub vision_fov: f32,
    pub hearing_range: f32,
}

impl From<SpawnEntityFullArgs> for super::Reducer {
    fn from(args: SpawnEntityFullArgs) -> Self {
        Self::SpawnEntityFull {
            pos_x: args.pos_x,
            pos_y: args.pos_y,
            agent_type: args.agent_type,
            rect_width: args.rect_width,
            rect_height: args.rect_height,
            color_r: args.color_r,
            color_g: args.color_g,
            color_b: args.color_b,
            color_a: args.color_a,
            label_name: args.label_name,
            team_id: args.team_id,
            max_hp: args.max_hp,
            vision_range: args.vision_range,
            vision_fov: args.vision_fov,
            hearing_range: args.hearing_range,
        }
    }
}

impl __sdk::InModule for SpawnEntityFullArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `spawn_entity_full`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait spawn_entity_full {
    /// Request that the remote module invoke the reducer `spawn_entity_full` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`spawn_entity_full:spawn_entity_full_then`] to run a callback after the reducer completes.
    fn spawn_entity_full(
        &self,
        pos_x: f32,
        pos_y: f32,
        agent_type: Option<AgentType>,
        rect_width: f32,
        rect_height: f32,
        color_r: f32,
        color_g: f32,
        color_b: f32,
        color_a: f32,
        label_name: String,
        team_id: u8,
        max_hp: f32,
        vision_range: f32,
        vision_fov: f32,
        hearing_range: f32,
    ) -> __sdk::Result<()> {
        self.spawn_entity_full_then(
            pos_x,
            pos_y,
            agent_type,
            rect_width,
            rect_height,
            color_r,
            color_g,
            color_b,
            color_a,
            label_name,
            team_id,
            max_hp,
            vision_range,
            vision_fov,
            hearing_range,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `spawn_entity_full` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn spawn_entity_full_then(
        &self,
        pos_x: f32,
        pos_y: f32,
        agent_type: Option<AgentType>,
        rect_width: f32,
        rect_height: f32,
        color_r: f32,
        color_g: f32,
        color_b: f32,
        color_a: f32,
        label_name: String,
        team_id: u8,
        max_hp: f32,
        vision_range: f32,
        vision_fov: f32,
        hearing_range: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl spawn_entity_full for super::RemoteReducers {
    fn spawn_entity_full_then(
        &self,
        pos_x: f32,
        pos_y: f32,
        agent_type: Option<AgentType>,
        rect_width: f32,
        rect_height: f32,
        color_r: f32,
        color_g: f32,
        color_b: f32,
        color_a: f32,
        label_name: String,
        team_id: u8,
        max_hp: f32,
        vision_range: f32,
        vision_fov: f32,
        hearing_range: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SpawnEntityFullArgs {
                pos_x,
                pos_y,
                agent_type,
                rect_width,
                rect_height,
                color_r,
                color_g,
                color_b,
                color_a,
                label_name,
                team_id,
                max_hp,
                vision_range,
                vision_fov,
                hearing_range,
            },
            callback,
        )
    }
}
