// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::speak_volume_type::SpeakVolume;
use super::speech_event_row_type::SpeechEventRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `speech_event`.
///
/// Obtain a handle from the [`SpeechEventTableAccess::speech_event`] method on [`super::RemoteTables`],
/// like `ctx.db.speech_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.speech_event().on_insert(...)`.
pub struct SpeechEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<SpeechEventRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `speech_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SpeechEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SpeechEventTableHandle`], which mediates access to the table `speech_event`.
    fn speech_event(&self) -> SpeechEventTableHandle<'_>;
}

impl SpeechEventTableAccess for super::RemoteTables {
    fn speech_event(&self) -> SpeechEventTableHandle<'_> {
        SpeechEventTableHandle {
            imp: self.imp.get_table::<SpeechEventRow>("speech_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SpeechEventInsertCallbackId(__sdk::CallbackId);
pub struct SpeechEventDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SpeechEventTableHandle<'ctx> {
    type Row = SpeechEventRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SpeechEventRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SpeechEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SpeechEventInsertCallbackId {
        SpeechEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SpeechEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SpeechEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SpeechEventDeleteCallbackId {
        SpeechEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SpeechEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SpeechEventUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SpeechEventTableHandle<'ctx> {
    type UpdateCallbackId = SpeechEventUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SpeechEventUpdateCallbackId {
        SpeechEventUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SpeechEventUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `event_id` unique index on the table `speech_event`,
/// which allows point queries on the field of the same name
/// via the [`SpeechEventEventIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.speech_event().event_id().find(...)`.
pub struct SpeechEventEventIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SpeechEventRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SpeechEventTableHandle<'ctx> {
    /// Get a handle on the `event_id` unique index on the table `speech_event`.
    pub fn event_id(&self) -> SpeechEventEventIdUnique<'ctx> {
        SpeechEventEventIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("event_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SpeechEventEventIdUnique<'ctx> {
    /// Find the subscribed row whose `event_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SpeechEventRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SpeechEventRow>("speech_event");
    _table.add_unique_constraint::<u64>("event_id", |row| &row.event_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SpeechEventRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SpeechEventRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SpeechEventRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait speech_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SpeechEventRow`.
    fn speech_event(&self) -> __sdk::__query_builder::Table<SpeechEventRow>;
}

impl speech_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn speech_event(&self) -> __sdk::__query_builder::Table<SpeechEventRow> {
        __sdk::__query_builder::Table::new("speech_event")
    }
}
