// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::speak_volume_type::SpeakVolume;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SpeechEventRow {
    pub event_id: u64,
    pub tick: u64,
    pub speaker_entity_id: u64,
    pub message: String,
    pub volume: SpeakVolume,
    pub pos_x: f32,
    pub pos_y: f32,
}

impl __sdk::InModule for SpeechEventRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SpeechEventRow`.
///
/// Provides typed access to columns for query building.
pub struct SpeechEventRowCols {
    pub event_id: __sdk::__query_builder::Col<SpeechEventRow, u64>,
    pub tick: __sdk::__query_builder::Col<SpeechEventRow, u64>,
    pub speaker_entity_id: __sdk::__query_builder::Col<SpeechEventRow, u64>,
    pub message: __sdk::__query_builder::Col<SpeechEventRow, String>,
    pub volume: __sdk::__query_builder::Col<SpeechEventRow, SpeakVolume>,
    pub pos_x: __sdk::__query_builder::Col<SpeechEventRow, f32>,
    pub pos_y: __sdk::__query_builder::Col<SpeechEventRow, f32>,
}

impl __sdk::__query_builder::HasCols for SpeechEventRow {
    type Cols = SpeechEventRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SpeechEventRowCols {
            event_id: __sdk::__query_builder::Col::new(table_name, "event_id"),
            tick: __sdk::__query_builder::Col::new(table_name, "tick"),
            speaker_entity_id: __sdk::__query_builder::Col::new(table_name, "speaker_entity_id"),
            message: __sdk::__query_builder::Col::new(table_name, "message"),
            volume: __sdk::__query_builder::Col::new(table_name, "volume"),
            pos_x: __sdk::__query_builder::Col::new(table_name, "pos_x"),
            pos_y: __sdk::__query_builder::Col::new(table_name, "pos_y"),
        }
    }
}

/// Indexed column accessor struct for the table `SpeechEventRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct SpeechEventRowIxCols {
    pub event_id: __sdk::__query_builder::IxCol<SpeechEventRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for SpeechEventRow {
    type IxCols = SpeechEventRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SpeechEventRowIxCols {
            event_id: __sdk::__query_builder::IxCol::new(table_name, "event_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SpeechEventRow {}
