// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SpriteRow {
    pub entity_id: u64,
    pub texture: String,
    pub frame: u32,
    pub layer: i32,
    pub color_r: f32,
    pub color_g: f32,
    pub color_b: f32,
    pub color_a: f32,
    pub visible: bool,
}

impl __sdk::InModule for SpriteRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SpriteRow`.
///
/// Provides typed access to columns for query building.
pub struct SpriteRowCols {
    pub entity_id: __sdk::__query_builder::Col<SpriteRow, u64>,
    pub texture: __sdk::__query_builder::Col<SpriteRow, String>,
    pub frame: __sdk::__query_builder::Col<SpriteRow, u32>,
    pub layer: __sdk::__query_builder::Col<SpriteRow, i32>,
    pub color_r: __sdk::__query_builder::Col<SpriteRow, f32>,
    pub color_g: __sdk::__query_builder::Col<SpriteRow, f32>,
    pub color_b: __sdk::__query_builder::Col<SpriteRow, f32>,
    pub color_a: __sdk::__query_builder::Col<SpriteRow, f32>,
    pub visible: __sdk::__query_builder::Col<SpriteRow, bool>,
}

impl __sdk::__query_builder::HasCols for SpriteRow {
    type Cols = SpriteRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SpriteRowCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            texture: __sdk::__query_builder::Col::new(table_name, "texture"),
            frame: __sdk::__query_builder::Col::new(table_name, "frame"),
            layer: __sdk::__query_builder::Col::new(table_name, "layer"),
            color_r: __sdk::__query_builder::Col::new(table_name, "color_r"),
            color_g: __sdk::__query_builder::Col::new(table_name, "color_g"),
            color_b: __sdk::__query_builder::Col::new(table_name, "color_b"),
            color_a: __sdk::__query_builder::Col::new(table_name, "color_a"),
            visible: __sdk::__query_builder::Col::new(table_name, "visible"),
        }
    }
}

/// Indexed column accessor struct for the table `SpriteRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct SpriteRowIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<SpriteRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for SpriteRow {
    type IxCols = SpriteRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SpriteRowIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SpriteRow {}
