// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::sprite_row_type::SpriteRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sprite`.
///
/// Obtain a handle from the [`SpriteTableAccess::sprite`] method on [`super::RemoteTables`],
/// like `ctx.db.sprite()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sprite().on_insert(...)`.
pub struct SpriteTableHandle<'ctx> {
    imp: __sdk::TableHandle<SpriteRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sprite`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SpriteTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SpriteTableHandle`], which mediates access to the table `sprite`.
    fn sprite(&self) -> SpriteTableHandle<'_>;
}

impl SpriteTableAccess for super::RemoteTables {
    fn sprite(&self) -> SpriteTableHandle<'_> {
        SpriteTableHandle {
            imp: self.imp.get_table::<SpriteRow>("sprite"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SpriteInsertCallbackId(__sdk::CallbackId);
pub struct SpriteDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SpriteTableHandle<'ctx> {
    type Row = SpriteRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SpriteRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SpriteInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SpriteInsertCallbackId {
        SpriteInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SpriteInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SpriteDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SpriteDeleteCallbackId {
        SpriteDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SpriteDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SpriteUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SpriteTableHandle<'ctx> {
    type UpdateCallbackId = SpriteUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SpriteUpdateCallbackId {
        SpriteUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SpriteUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `sprite`,
/// which allows point queries on the field of the same name
/// via the [`SpriteEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sprite().entity_id().find(...)`.
pub struct SpriteEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SpriteRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SpriteTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `sprite`.
    pub fn entity_id(&self) -> SpriteEntityIdUnique<'ctx> {
        SpriteEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SpriteEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SpriteRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SpriteRow>("sprite");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SpriteRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SpriteRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SpriteRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait spriteQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SpriteRow`.
    fn sprite(&self) -> __sdk::__query_builder::Table<SpriteRow>;
}

impl spriteQueryTableAccess for __sdk::QueryTableAccessor {
    fn sprite(&self) -> __sdk::__query_builder::Table<SpriteRow> {
        __sdk::__query_builder::Table::new("sprite")
    }
}
