// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::ability_target_kind_type::AbilityTargetKind;
use super::action_kind_type::ActionKind;
use super::speak_volume_type::SpeakVolume;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SubmitActionArgs {
    pub entity_id: u64,
    pub action_kind: ActionKind,
    pub direction_x: Option<f32>,
    pub direction_y: Option<f32>,
    pub angle: Option<f32>,
    pub target_x: Option<f32>,
    pub target_y: Option<f32>,
    pub target_entity_id: Option<u64>,
    pub ability_slot: Option<u8>,
    pub ability_target_kind: Option<AbilityTargetKind>,
    pub message: Option<String>,
    pub volume: Option<SpeakVolume>,
    pub signal_type: Option<String>,
    pub signal_data: Option<String>,
    pub prefab: Option<String>,
}

impl From<SubmitActionArgs> for super::Reducer {
    fn from(args: SubmitActionArgs) -> Self {
        Self::SubmitAction {
            entity_id: args.entity_id,
            action_kind: args.action_kind,
            direction_x: args.direction_x,
            direction_y: args.direction_y,
            angle: args.angle,
            target_x: args.target_x,
            target_y: args.target_y,
            target_entity_id: args.target_entity_id,
            ability_slot: args.ability_slot,
            ability_target_kind: args.ability_target_kind,
            message: args.message,
            volume: args.volume,
            signal_type: args.signal_type,
            signal_data: args.signal_data,
            prefab: args.prefab,
        }
    }
}

impl __sdk::InModule for SubmitActionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `submit_action`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait submit_action {
    /// Request that the remote module invoke the reducer `submit_action` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`submit_action:submit_action_then`] to run a callback after the reducer completes.
    fn submit_action(
        &self,
        entity_id: u64,
        action_kind: ActionKind,
        direction_x: Option<f32>,
        direction_y: Option<f32>,
        angle: Option<f32>,
        target_x: Option<f32>,
        target_y: Option<f32>,
        target_entity_id: Option<u64>,
        ability_slot: Option<u8>,
        ability_target_kind: Option<AbilityTargetKind>,
        message: Option<String>,
        volume: Option<SpeakVolume>,
        signal_type: Option<String>,
        signal_data: Option<String>,
        prefab: Option<String>,
    ) -> __sdk::Result<()> {
        self.submit_action_then(
            entity_id,
            action_kind,
            direction_x,
            direction_y,
            angle,
            target_x,
            target_y,
            target_entity_id,
            ability_slot,
            ability_target_kind,
            message,
            volume,
            signal_type,
            signal_data,
            prefab,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `submit_action` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn submit_action_then(
        &self,
        entity_id: u64,
        action_kind: ActionKind,
        direction_x: Option<f32>,
        direction_y: Option<f32>,
        angle: Option<f32>,
        target_x: Option<f32>,
        target_y: Option<f32>,
        target_entity_id: Option<u64>,
        ability_slot: Option<u8>,
        ability_target_kind: Option<AbilityTargetKind>,
        message: Option<String>,
        volume: Option<SpeakVolume>,
        signal_type: Option<String>,
        signal_data: Option<String>,
        prefab: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl submit_action for super::RemoteReducers {
    fn submit_action_then(
        &self,
        entity_id: u64,
        action_kind: ActionKind,
        direction_x: Option<f32>,
        direction_y: Option<f32>,
        angle: Option<f32>,
        target_x: Option<f32>,
        target_y: Option<f32>,
        target_entity_id: Option<u64>,
        ability_slot: Option<u8>,
        ability_target_kind: Option<AbilityTargetKind>,
        message: Option<String>,
        volume: Option<SpeakVolume>,
        signal_type: Option<String>,
        signal_data: Option<String>,
        prefab: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SubmitActionArgs {
                entity_id,
                action_kind,
                direction_x,
                direction_y,
                angle,
                target_x,
                target_y,
                target_entity_id,
                ability_slot,
                ability_target_kind,
                message,
                volume,
                signal_type,
                signal_data,
                prefab,
            },
            callback,
        )
    }
}
