// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TransformRow {
    pub entity_id: u64,
    pub pos_x: f32,
    pub pos_y: f32,
    pub rotation: f32,
    pub scale_x: f32,
    pub scale_y: f32,
}

impl __sdk::InModule for TransformRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TransformRow`.
///
/// Provides typed access to columns for query building.
pub struct TransformRowCols {
    pub entity_id: __sdk::__query_builder::Col<TransformRow, u64>,
    pub pos_x: __sdk::__query_builder::Col<TransformRow, f32>,
    pub pos_y: __sdk::__query_builder::Col<TransformRow, f32>,
    pub rotation: __sdk::__query_builder::Col<TransformRow, f32>,
    pub scale_x: __sdk::__query_builder::Col<TransformRow, f32>,
    pub scale_y: __sdk::__query_builder::Col<TransformRow, f32>,
}

impl __sdk::__query_builder::HasCols for TransformRow {
    type Cols = TransformRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TransformRowCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            pos_x: __sdk::__query_builder::Col::new(table_name, "pos_x"),
            pos_y: __sdk::__query_builder::Col::new(table_name, "pos_y"),
            rotation: __sdk::__query_builder::Col::new(table_name, "rotation"),
            scale_x: __sdk::__query_builder::Col::new(table_name, "scale_x"),
            scale_y: __sdk::__query_builder::Col::new(table_name, "scale_y"),
        }
    }
}

/// Indexed column accessor struct for the table `TransformRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct TransformRowIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<TransformRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for TransformRow {
    type IxCols = TransformRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TransformRowIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TransformRow {}
