// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::velocity_row_type::VelocityRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `velocity`.
///
/// Obtain a handle from the [`VelocityTableAccess::velocity`] method on [`super::RemoteTables`],
/// like `ctx.db.velocity()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.velocity().on_insert(...)`.
pub struct VelocityTableHandle<'ctx> {
    imp: __sdk::TableHandle<VelocityRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `velocity`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VelocityTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VelocityTableHandle`], which mediates access to the table `velocity`.
    fn velocity(&self) -> VelocityTableHandle<'_>;
}

impl VelocityTableAccess for super::RemoteTables {
    fn velocity(&self) -> VelocityTableHandle<'_> {
        VelocityTableHandle {
            imp: self.imp.get_table::<VelocityRow>("velocity"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VelocityInsertCallbackId(__sdk::CallbackId);
pub struct VelocityDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for VelocityTableHandle<'ctx> {
    type Row = VelocityRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = VelocityRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VelocityInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VelocityInsertCallbackId {
        VelocityInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VelocityInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VelocityDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VelocityDeleteCallbackId {
        VelocityDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VelocityDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct VelocityUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for VelocityTableHandle<'ctx> {
    type UpdateCallbackId = VelocityUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VelocityUpdateCallbackId {
        VelocityUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VelocityUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `velocity`,
/// which allows point queries on the field of the same name
/// via the [`VelocityEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.velocity().entity_id().find(...)`.
pub struct VelocityEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<VelocityRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> VelocityTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `velocity`.
    pub fn entity_id(&self) -> VelocityEntityIdUnique<'ctx> {
        VelocityEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> VelocityEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<VelocityRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<VelocityRow>("velocity");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<VelocityRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<VelocityRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `VelocityRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait velocityQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `VelocityRow`.
    fn velocity(&self) -> __sdk::__query_builder::Table<VelocityRow>;
}

impl velocityQueryTableAccess for __sdk::QueryTableAccessor {
    fn velocity(&self) -> __sdk::__query_builder::Table<VelocityRow> {
        __sdk::__query_builder::Table::new("velocity")
    }
}
