// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct VelocityRow {
    pub entity_id: u64,
    pub linear_x: f32,
    pub linear_y: f32,
    pub angular: f32,
}

impl __sdk::InModule for VelocityRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `VelocityRow`.
///
/// Provides typed access to columns for query building.
pub struct VelocityRowCols {
    pub entity_id: __sdk::__query_builder::Col<VelocityRow, u64>,
    pub linear_x: __sdk::__query_builder::Col<VelocityRow, f32>,
    pub linear_y: __sdk::__query_builder::Col<VelocityRow, f32>,
    pub angular: __sdk::__query_builder::Col<VelocityRow, f32>,
}

impl __sdk::__query_builder::HasCols for VelocityRow {
    type Cols = VelocityRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        VelocityRowCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            linear_x: __sdk::__query_builder::Col::new(table_name, "linear_x"),
            linear_y: __sdk::__query_builder::Col::new(table_name, "linear_y"),
            angular: __sdk::__query_builder::Col::new(table_name, "angular"),
        }
    }
}

/// Indexed column accessor struct for the table `VelocityRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct VelocityRowIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<VelocityRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for VelocityRow {
    type IxCols = VelocityRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        VelocityRowIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for VelocityRow {}
