// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::world_event_kind_type::WorldEventKind;
use super::world_event_row_type::WorldEventRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `world_event`.
///
/// Obtain a handle from the [`WorldEventTableAccess::world_event`] method on [`super::RemoteTables`],
/// like `ctx.db.world_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_event().on_insert(...)`.
pub struct WorldEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<WorldEventRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `world_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WorldEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WorldEventTableHandle`], which mediates access to the table `world_event`.
    fn world_event(&self) -> WorldEventTableHandle<'_>;
}

impl WorldEventTableAccess for super::RemoteTables {
    fn world_event(&self) -> WorldEventTableHandle<'_> {
        WorldEventTableHandle {
            imp: self.imp.get_table::<WorldEventRow>("world_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WorldEventInsertCallbackId(__sdk::CallbackId);
pub struct WorldEventDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WorldEventTableHandle<'ctx> {
    type Row = WorldEventRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorldEventRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WorldEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldEventInsertCallbackId {
        WorldEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorldEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WorldEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldEventDeleteCallbackId {
        WorldEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorldEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct WorldEventUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WorldEventTableHandle<'ctx> {
    type UpdateCallbackId = WorldEventUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorldEventUpdateCallbackId {
        WorldEventUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorldEventUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `event_id` unique index on the table `world_event`,
/// which allows point queries on the field of the same name
/// via the [`WorldEventEventIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_event().event_id().find(...)`.
pub struct WorldEventEventIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WorldEventRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WorldEventTableHandle<'ctx> {
    /// Get a handle on the `event_id` unique index on the table `world_event`.
    pub fn event_id(&self) -> WorldEventEventIdUnique<'ctx> {
        WorldEventEventIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("event_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WorldEventEventIdUnique<'ctx> {
    /// Find the subscribed row whose `event_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<WorldEventRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WorldEventRow>("world_event");
    _table.add_unique_constraint::<u64>("event_id", |row| &row.event_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<WorldEventRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WorldEventRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `WorldEventRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait world_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `WorldEventRow`.
    fn world_event(&self) -> __sdk::__query_builder::Table<WorldEventRow>;
}

impl world_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn world_event(&self) -> __sdk::__query_builder::Table<WorldEventRow> {
        __sdk::__query_builder::Table::new("world_event")
    }
}
