// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::world_event_kind_type::WorldEventKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WorldEventRow {
    pub event_id: u64,
    pub tick: u64,
    pub event_kind: WorldEventKind,
    pub entity_id: u64,
    pub secondary_entity_id: Option<u64>,
    pub data_json: String,
}

impl __sdk::InModule for WorldEventRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `WorldEventRow`.
///
/// Provides typed access to columns for query building.
pub struct WorldEventRowCols {
    pub event_id: __sdk::__query_builder::Col<WorldEventRow, u64>,
    pub tick: __sdk::__query_builder::Col<WorldEventRow, u64>,
    pub event_kind: __sdk::__query_builder::Col<WorldEventRow, WorldEventKind>,
    pub entity_id: __sdk::__query_builder::Col<WorldEventRow, u64>,
    pub secondary_entity_id: __sdk::__query_builder::Col<WorldEventRow, Option<u64>>,
    pub data_json: __sdk::__query_builder::Col<WorldEventRow, String>,
}

impl __sdk::__query_builder::HasCols for WorldEventRow {
    type Cols = WorldEventRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WorldEventRowCols {
            event_id: __sdk::__query_builder::Col::new(table_name, "event_id"),
            tick: __sdk::__query_builder::Col::new(table_name, "tick"),
            event_kind: __sdk::__query_builder::Col::new(table_name, "event_kind"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            secondary_entity_id: __sdk::__query_builder::Col::new(
                table_name,
                "secondary_entity_id",
            ),
            data_json: __sdk::__query_builder::Col::new(table_name, "data_json"),
        }
    }
}

/// Indexed column accessor struct for the table `WorldEventRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct WorldEventRowIxCols {
    pub event_id: __sdk::__query_builder::IxCol<WorldEventRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for WorldEventRow {
    type IxCols = WorldEventRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WorldEventRowIxCols {
            event_id: __sdk::__query_builder::IxCol::new(table_name, "event_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for WorldEventRow {}
