// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
#[derive(Copy, Eq, Hash)]
pub enum WorldEventKind {
    EntitySpawned,

    EntityDespawned,

    EntityDied,

    InteractionTriggered,

    ItemPickedUp,

    ItemDropped,

    AbilityUsed,

    WorldCreated,

    WorldReset,

    TickAdvanced,
}

impl __sdk::InModule for WorldEventKind {
    type Module = super::RemoteModule;
}
