// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WorldStateRow {
    pub id: u32,
    pub tick: u64,
    pub rng_seed: u64,
    pub ticks_per_second: u32,
    pub world_width: f32,
    pub world_height: f32,
    pub max_entities: u32,
    pub paused: bool,
}

impl __sdk::InModule for WorldStateRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `WorldStateRow`.
///
/// Provides typed access to columns for query building.
pub struct WorldStateRowCols {
    pub id: __sdk::__query_builder::Col<WorldStateRow, u32>,
    pub tick: __sdk::__query_builder::Col<WorldStateRow, u64>,
    pub rng_seed: __sdk::__query_builder::Col<WorldStateRow, u64>,
    pub ticks_per_second: __sdk::__query_builder::Col<WorldStateRow, u32>,
    pub world_width: __sdk::__query_builder::Col<WorldStateRow, f32>,
    pub world_height: __sdk::__query_builder::Col<WorldStateRow, f32>,
    pub max_entities: __sdk::__query_builder::Col<WorldStateRow, u32>,
    pub paused: __sdk::__query_builder::Col<WorldStateRow, bool>,
}

impl __sdk::__query_builder::HasCols for WorldStateRow {
    type Cols = WorldStateRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WorldStateRowCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            tick: __sdk::__query_builder::Col::new(table_name, "tick"),
            rng_seed: __sdk::__query_builder::Col::new(table_name, "rng_seed"),
            ticks_per_second: __sdk::__query_builder::Col::new(table_name, "ticks_per_second"),
            world_width: __sdk::__query_builder::Col::new(table_name, "world_width"),
            world_height: __sdk::__query_builder::Col::new(table_name, "world_height"),
            max_entities: __sdk::__query_builder::Col::new(table_name, "max_entities"),
            paused: __sdk::__query_builder::Col::new(table_name, "paused"),
        }
    }
}

/// Indexed column accessor struct for the table `WorldStateRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct WorldStateRowIxCols {
    pub id: __sdk::__query_builder::IxCol<WorldStateRow, u32>,
}

impl __sdk::__query_builder::HasIxCols for WorldStateRow {
    type IxCols = WorldStateRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WorldStateRowIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for WorldStateRow {}
