// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::world_state_row_type::WorldStateRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `world_state`.
///
/// Obtain a handle from the [`WorldStateTableAccess::world_state`] method on [`super::RemoteTables`],
/// like `ctx.db.world_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_state().on_insert(...)`.
pub struct WorldStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<WorldStateRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `world_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WorldStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WorldStateTableHandle`], which mediates access to the table `world_state`.
    fn world_state(&self) -> WorldStateTableHandle<'_>;
}

impl WorldStateTableAccess for super::RemoteTables {
    fn world_state(&self) -> WorldStateTableHandle<'_> {
        WorldStateTableHandle {
            imp: self.imp.get_table::<WorldStateRow>("world_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WorldStateInsertCallbackId(__sdk::CallbackId);
pub struct WorldStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WorldStateTableHandle<'ctx> {
    type Row = WorldStateRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorldStateRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WorldStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldStateInsertCallbackId {
        WorldStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorldStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WorldStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldStateDeleteCallbackId {
        WorldStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorldStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct WorldStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WorldStateTableHandle<'ctx> {
    type UpdateCallbackId = WorldStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorldStateUpdateCallbackId {
        WorldStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorldStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `world_state`,
/// which allows point queries on the field of the same name
/// via the [`WorldStateIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_state().id().find(...)`.
pub struct WorldStateIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WorldStateRow, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WorldStateTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `world_state`.
    pub fn id(&self) -> WorldStateIdUnique<'ctx> {
        WorldStateIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WorldStateIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<WorldStateRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WorldStateRow>("world_state");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<WorldStateRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WorldStateRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `WorldStateRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait world_stateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `WorldStateRow`.
    fn world_state(&self) -> __sdk::__query_builder::Table<WorldStateRow>;
}

impl world_stateQueryTableAccess for __sdk::QueryTableAccessor {
    fn world_state(&self) -> __sdk::__query_builder::Table<WorldStateRow> {
        __sdk::__query_builder::Table::new("world_state")
    }
}
